### ISSUE TITLE
don't show inlay hints for arguments on variables with the same name

### ISSUE THREAD

**Issue by DetachHead** [DetachHead/basedpyright#135]
![image](https://github.com/DetachHead/basedpyright/assets/57028336/c111d8e3-33c0-4700-89fe-3a7bf4bfe113)

**Comment by KotlinIsland** [comment]
Generally, inlays don't show up if the value is a simple symbol.

**Comment by DetachHead** [comment]
how would you define "simple"

**Comment by KotlinIsland** [comment]
just a symbol vs a different kind of expression
`f(a)` don't show
`f(a + 1)` show

**Comment by DetachHead** [comment]
eh, i think just based on whether the variable name matches and whether the function takes only one argument (#137) is good
