### ISSUE TITLE
Add extension to Open VSX Registry

### ISSUE THREAD

**Issue by matgd** [DetachHead/basedpyright#166]
Due to Microsoft's policy, extensions added to the VSCode marketplace cannot be used in other tools (_you may only install and use Marketplace Offerings with Visual Studio Products and Services_). 
For example, [VSCodium](https://vscodium.com/) cannot use this extension:
https://github.com/VSCodium/vscodium?tab=readme-ov-file#extensions-and-the-marketplace

Adding this extension to [Open VSX Registry](https://open-vsx.org/) would make it much easier to use it in tools like VSCodium.

**Comment by KotlinIsland** [comment]
Basedpyrightium

**Comment by matgd** [comment]
Much thanks!
