### ISSUE TITLE
Invalid glibc versions.

### ISSUE THREAD

**Issue by cazador481** [DetachHead/basedpyright#167]
I am getting invalid glibc versions with the build in version of node.  I would like to use my own version of node that is installed on my machine.
```
/home/scratch.eash/.pipx/venvs/basedpyright/lib/python3.9/site-packages/nodejs/bin/node: /lib64/libm.so.6: version `GLIBC_2.27' not found (required by /home/scratch.eash/.pipx/venvs/basedpyright/lib/python3.9/site-packages/nodejs/bin/node)
/home/scratch.eash/.pipx/venvs/basedpyright/lib/python3.9/site-packages/nodejs/bin/node: /lib64/libc.so.6: version `GLIBC_2.25' not found (required by /home/scratch.eash/.pipx/venvs/basedpyright/lib/python3.9/site-packages/nodejs/bin/node)
/home/scratch.eash/.pipx/venvs/basedpyright/lib/python3.9/site-packages/nodejs/bin/node: /lib64/libc.so.6: version `GLIBC_2.28' not found (required by /home/scratch.eash/.pipx/venvs/basedpyright/lib/python3.9/site-packages/nodejs/bin/node)
/home/scratch.eash/.pipx/venvs/basedpyright/lib/python3.9/site-packages/nodejs/bin/node: /lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /home/scratch.eash/.pipx/venvs/basedpyright/lib/python3.9/site-packages/nodejs/bin/node)
/home/scratch.eash/.pipx/venvs/basedpyright/lib/python3.9/site-packages/nodejs/bin/node: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /home/scratch.eash/.pipx/venvs/basedpyright/lib/python3.9/site-packages/nodejs/bin/node)
/home/scratch.eash/.pipx/venvs/basedpyright/lib/python3.9/site-packages/nodejs/bin/node: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /home/scratch.eash/.pipx/venvs/basedpyright/lib/python3.9/site-packages/nodejs/bin/node)
```

**Comment by DetachHead** [comment]
what OS are you using?

the point of having the node version bundled with the pypi package is that the user shouldn't have to worry about installing it themselves. i see nodejs as an implementation detail that shouldn't be exposed to the user, so hopefully i can find a solution that doesn't require allowing the user to specify a globally installed node

**Comment by cazador481** [comment]
I am on an ancient os. Centos 7.5

**Comment by DetachHead** [comment]
looks like that's the issue. basedpyright comes with node 18 but i think your centOS version is too old for that. https://stackoverflow.com/a/72038045

since both centOS and node 16 are EOL i was originally going to close this issue, but then i realized upstream pyright supports node 14 so i should probably try to match that.

can you install the version from https://github.com/DetachHead/basedpyright/pull/204 and see if that fixes it?
```
pip install git+https://github.com/detachhead/basedpyright@support-node14
```

**Comment by lewis6991** [comment]
https://pypi.org/project/nodejs-wheel/ supports a much older glibc version and can confirm it work on rhel7 (similar to centos7). Would it be possible to switch to (or optionally use) that instead?

**Comment by DetachHead** [comment]
thanks for the suggestion, we can give it a go. [the one we currently use](https://pypi.org/project/nodejs-bin/) looks abandoned so i was already keeping an eye out for another solution anyway
