### ISSUE TITLE
NixOS Support

### ISSUE THREAD

**Issue by znd4** [DetachHead/basedpyright#177]
The bundled node fails to run on NixOS:

```
Could not start dynamically linked executable: /home/znd4/Projects/far.ai-interview/.direnv/python-3.11/lib/python3.11/site-packages/nodejs/bin/node
NixOS cannot run dynamically linked executables intended for generic\nlinux environments out of the box. For more information, see:
https://nix.dev/permalink/stub-ld
```

I'd understand closing this issue, but I thought I'd at least leave some breadcrumbs for future me / anyone else who wants to take a crack at packaging this really cool looking project for Nix:

- [one of dream2nix's node packaging modules](https://nix-community.github.io/dream2nix/options/nodejs-granular-v3.html) might be useful
- [something simpler](https://github.com/adisbladis/buildNodeModules) might work though :shrug: 

Unfortunately, my node experience is pretty thin, so this might be tricky

**Comment by DetachHead** [comment]
can you please check if #323 fixes this?
```
pip install git+https://github.com/DetachHead/basedpyright@fa71759782c1d3b97eae50504711d670739208d7
```
(note that it will probably take several minutes to install due to #335)

**Comment by leiserfg** [comment]
By now I'm using `https://github.com/leiserfg/leiserfg-overlay/blob/master/pkgs/basedpyright/default.nix`

**Comment by DetachHead** [comment]
so that just patches it to use a different node binary. i don't know anything about nix but is it a problem with the node binary we're using that can be raised upstream at https://github.com/njzjz/nodejs-wheel?

**Comment by DetachHead** [comment]
do you think that's a decent solution? we can add a "nixOS" section in [the installation instructions](https://github.com/DetachHead/basedpyright/blob/main/docs/installation.md) that says to install it from [your repo](https://github.com/leiserfg/leiserfg-overlay/blob/master/pkgs/basedpyright/default.nix)

**Comment by leiserfg** [comment]
I could add a flake to your repo if you like so, but it will have to be in the weekend.

**Comment by DetachHead** [comment]
sounds good, thanks

**Comment by leiserfg** [comment]
@DetachHead  then it's better to wait for the work from @kiike  to be merged.

**Comment by DetachHead** [comment]
thanks! if you don't mind would you like to also write some [installation instructions](https://github.com/DetachHead/basedpyright/blob/main/docs/installation.md) for nixOS?
