### ISSUE TITLE
Support `defaultLibrary` semantic token modifiers

### ISSUE THREAD

**Issue by ValdezFOmar** [DetachHead/basedpyright#188]
This will help distinguish user defined functions/classes from builtin ones. 
Right now they are highlighted the same:

![image](https://github.com/DetachHead/basedpyright/assets/80359343/b3bbf70b-c9d0-4e69-b5e1-5ffe4d9370de)

**Comment by KotlinIsland** [comment]
I'm curious, how do other python LSPs handle this? as per https://github.com/DetachHead/basedpyright/pull/193#issuecomment-2017199835, Pylance defines a custom modifier `builtin`.
