### ISSUE TITLE
Please add option for global pyproject.toml

### ISSUE THREAD

**Issue by KraXen72** [DetachHead/basedpyright#190]
Some options like reportMissingTypeStubs are not configurable from `basedpyright.*` in `settings.json`. I already have a global pyproject.toml/some toml file for ruff, i'd like to just add the stuff there and use it for projects unless they specify otherwise in their `pyproject.toml`. 
Thanks!

**Comment by DetachHead** [comment]
`reportMissingTypeStubs` is configurable from `settings.json`, does this work for you?

```json
{
    "basedpyright.analysis.diagnosticSeverityOverrides": {
        "reportMissingTypeStubs": "error"
    }
}
```

tbh i'm not really a fan of global config and have been considering deprecating/removing the ability to configure the rules in `settings.json`. imo the config should always be configured at the project level. that way, other developers working on the project will have the same config as everybody else, and the CI can be configured to use it too.

**Comment by KraXen72** [comment]
Yes, it does work! thanks!
I'm fine with moving to a toml based config, but please do not remove global config all together.
Usually, the only developer on the project is me.
for example, this is how i set the global config for ruff:
```jsonc
"ruff.lint.args": [
    "--config=D:/coding/python/ruff.toml"
],
```

**Comment by DetachHead** [comment]
fair enough, i'll leave the global config as-is
