### ISSUE TITLE
Set `python.languageServer` to `"None"` automatically

### ISSUE THREAD

**Issue by KotlinIsland** [DetachHead/basedpyright#200]
You would NEVER want this set.

**Comment by DetachHead** [comment]
to clarify, this setting is for the language server used by the python vscode extension, which defaults to pylance but also has options for jedi and i think some others. 

basedpyright does not appear in the list, and all of those options just conflict with it. so it should always be disabled

**Comment by DetachHead** [comment]
did this ages ago 5985914279a0a8d8b060a8f81e18a67c41c580e1
