### ISSUE TITLE
import suggestion code action is dependent on where the cursor is on the symbol

### ISSUE THREAD

**Issue by haarisr** [DetachHead/basedpyright#206]
The code action works the first time. If I delete the import statement suggested by the action and reuse it again, the code action does not work again. I just get no code actions available.

This is on neovim

**Comment by DetachHead** [comment]
can't seem to reproduce this in vscode, perhaps it's a neovim specific issue? do other code actions or other language servers have the same issue?

**Comment by haarisr** [comment]
Interesting, I played with it a little more.It does work the second time.

The issue seems to be that the code action has to be triggered at the end of the word.

Triggering it at the start of the word, does not return anything.
Triggering it at the middle of the word, returns false positives.

**Comment by DetachHead** [comment]
oh yeah, i noticed that too
