### ISSUE TITLE
Inlay hints being shown multiple times

### ISSUE THREAD

**Issue by kiyoon** [DetachHead/basedpyright#207]
<img width="1326" alt="image" src="https://github.com/DetachHead/basedpyright/assets/12980409/45f28098-6fb4-4d31-be6e-4819ddd1db32">

In my neovim 0.9.5 setup, the inlay hints are shown multiple times with basedpyright.  
It might be the problem with the [lvimuser/lsp-inlayhints.nvim](https://github.com/lvimuser/lsp-inlayhints.nvim), but no other LSP I've used had this problem so far.

I don't know much about LSP and I thought it may be related to the implementation details in basedpyright not being compatible with all client, thus I'm posting the issue here.

Personally, I like inlay hints as a virtual text, and they shouldn't be inserted in the middle of the text. Thus I'm using the plugin and not the neovim 0.10 built-in.

**Comment by kiyoon** [comment]
I don't know if it's related, but I found a related issue.

When requesting inlay hints to the server, the server doesn't respect the range.  
In the below example, when `params['range']` is defined the server needs to response regarding that.

```lua
client.request("textDocument/inlayHint", params, callback, bufnr)
```

Here is the full code to reproduce. Calling `:InlayTypeHint` should only print current line information, but basedpyright reports in all range.

```lua
local function get_inlay_hint_params(client, bufnr, line)
  local params = {
    textDocument = vim.lsp.util.make_text_document_params(bufnr),
    range = {
      start = {
        line = 0,
        character = 0,
      },
      ["end"] = {
        line = 0,
        character = 0,
      },
    },
  }

  if line == nil then
    local line_count = vim.api.nvim_buf_line_count(bufnr) - 1
    local last_line = vim.api.nvim_buf_get_lines(bufnr, line_count, line_count + 1, true)

    params["range"]["end"]["line"] = line_count
    params["range"]["end"]["character"] =
      vim.lsp.util.character_offset(bufnr, line_count, #last_line[1], client.offset_encoding)
  else
    local current_line = vim.api.nvim_buf_get_lines(bufnr, line, line + 1, true)
    params["range"]["start"]["line"] = line
    params["range"]["end"]["line"] = line
    params["range"]["end"]["character"] =
      vim.lsp.util.character_offset(bufnr, line, #current_line[1], client.offset_encoding)
    vim.print(params)
  end

  return params
end

local function request_all_inlay_hints(client, bufnr, callback)
  client.request("textDocument/inlayHint", get_inlay_hint_params(client, bufnr), callback, bufnr)
end

local function request_current_line_inlay_hints(client, callback)
  local bufnr = vim.api.nvim_get_current_buf()
  local current_line = vim.api.nvim_win_get_cursor(0)[1] - 1
  client.request("textDocument/inlayHint", get_inlay_hint_params(client, bufnr, current_line), callback, bufnr)
end

-- Parses the result into a easily usable format
-- example:
-- {
--  ["12"] = { {
--      kind = "TypeHint",
--      label = "String"
--    } },
--  ["13"] = { {
--      kind = "TypeHint",
--      label = "usize"
--    } },
-- }
--
local function parse_hints(result)
  local map = {}

  if type(result) ~= "table" then
    return {}
  end

  for _, value in pairs(result) do
    local range = value.position
    local line = value.position.line
    local label = value.label

    local label_str = ""

    if type(label) == "string" then
      label_str = value.label
    elseif type(label) == "table" then
      for _, label_part in ipairs(label) do
        label_str = label_str .. label_part.value
      end
    end

    local kind = value.kind

    if map[line] ~= nil then
      table.insert(map[line], {
        label = label_str,
        kind = kind,
        range = range,
      })
    else
      map[line] = {
        { label = label_str, kind = kind, range = range },
      }
    end

    table.sort(map[line], function(a, b)
      return a.range.character < b.range.character
    end)
  end

  return map
end

local function print_inlay_hint_current_line()
  local clients = vim.lsp.get_active_clients { bufnr = 0 }
  if not next(clients) then
    return
  end

  for _, client in ipairs(clients) do
    request_current_line_inlay_hints(client, function(err, result, ctx)
      if err then
        return
      end

      local hints = parse_hints(result)
      vim.print(hints)
    end)
  end
end

vim.api.nvim_create_user_command("InlayTypeHint", function()
  print_inlay_hint_current_line()
end, {})
```

**Comment by kiyoon** [comment]
The range was the problem. I managed to solve this issue by forking the inlay hints plugin <https://github.com/kiyoon/lsp-inlayhints.nvim> and filtering out the range from the response. It would be nice if basedpyright can fix the issue itself, but it's good enough for me now. Thanks for the wonderful project.

**Comment by DetachHead** [comment]
thanks for investigating. i'm fairly new to language server stuff and as a vscode user i just did whatever seemed to work in the vscode extension. i will try to see if i can figure out how to fix it on my end, but if you or someone else knows how to fix it a PR would be appreciated

**Comment by kiyoon** [comment]
@DetachHead I'm not familiar with TypeScript, but what I found is that when a client requests for inlay hints, there will be a parameter called `range` and the server should return the hints only within the given range. It looks like `inlayHintsProvider.ts` file can address the issue but I don't know where the parameters are coming from 🤣

**Comment by kiyoon** [comment]
https://github.com/jbradaric/pyright-inlay-hints/blob/5d697116b4ac32507628f59b6cb0ff28c26de6fd/packages/pyright-internal/src/languageService/inlayHintsProvider.ts#L44C1-L48C14

I think this bit is missing.

**Comment by DetachHead** [comment]
can you see if #209 fixes it?

```
pip install git+://github.com/DetachHead/basedpyright@inlay-hint-range-fix
```

**Comment by kiyoon** [comment]
Thanks for addressing this!

I tried the above example code to get the inlay hint on the current line. It returns two, one is the function return type, and the other is the actual line.

Below examples show the input params and the output response it got from the LSP. (3 different places)

```lua
{
  range = {
    ["end"] = {
      character = 29,
      line = 715
    },
    start = {
      character = 0,
      line = 715
    }
  },
  textDocument = {
    uri = "file:///home/kiyoon/project/dti-pytorch/src/dti/cli/inference_module.py"
  }
}
{
  [685] = { {
      kind = 1,
      label = "-> None",
      range = {
        character = 1,
        line = 685
      }
    } },
  [715] = { {
      kind = 1,
      label = ": Trainer",
      range = {
        character = 15,
        line = 715
      }
    } }
}
```

```lua
{
  range = {
    ["end"] = {
      character = 68,
      line = 686
    },
    start = {
      character = 0,
      line = 686
    }
  },
  textDocument = {
    uri = "file:///home/kiyoon/project/dti-pytorch/src/dti/cli/inference_module.py"
  }
}
{
  [685] = { {
      kind = 1,
      label = "-> None",
      range = {
        character = 1,
        line = 685
      }
    } },
  [686] = { {
      kind = 1,
      label = ": str | None",
      range = {
        character = 16,
        line = 686
      }
    } }
}
```

```lua
{
  range = {
    ["end"] = {
      character = 70,
      line = 589
    },
    start = {
      character = 0,
      line = 589
    }
  },
  textDocument = {
    uri = "file:///home/kiyoon/project/dti-pytorch/src/dti/cli/inference_module.py"
  }
}
{
  [587] = { {
      kind = 1,
      label = "-> None",
      range = {
        character = 49,
        line = 587
      }
    } },
  [589] = { {
      kind = 1,
      label = ": list[str]",
      range = {
        character = 14,
        line = 589
      }
    } }
}
```

Initially, I thought it wasn't supposed to, so I checked the behaviour of `lua_ls` and it does a similar thing: returning both function types and the variable type. It seems that the inlay hints plugin works correctly as well.
