### ISSUE TITLE
Support `__builtins__`

### ISSUE THREAD

**Issue by KotlinIsland** [DetachHead/basedpyright#208]
```py
reveal_type(__builtins__.int)  # Any
```

**Comment by DetachHead** [comment]
since `__builtins__` is an implementation detail and can be different depending on the python implementation, i dont think its worth supporting it, when there are better ways to access the builtins module (eg. `from builtins import int`)

**Comment by KotlinIsland** [comment]
Additionally, sometimes it is a module, and sometimes it is a `dict`
