### ISSUE TITLE
semantic highlighter does not recognize forward references used in generic parameters

### ISSUE THREAD

**Issue by sena-nana** [DetachHead/basedpyright#210]
### Version:
BasedPyright v1.7.0 in VSCode

### Content: 
I have encountered an issue while using BasedPyright. It seems that BasedPyright does not correctly recognize and highlight forward references when used in generic parameters.And Pylance Also has this problem.

Here is the code where I encountered the issue:
```python
# filename:temp1.py

class C:...

# filename:temp.py
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from temp1 import C

class A[T]:
    def __init__(self, t: T):...

class B(A["C"]):...
```
In this code, I used a forward reference "C" in class B(A["C"]):.... However, BasedPyright does not highlight "C" and does not consider it as a used reference,because ruff reports "`temp1.C` imported but unused".But when B's init is called, you can see that the generic T is already recognized as "C".

If additional information is needed, I will assist

**Comment by DetachHead** [comment]
need to also add support for go to definition and import suggestions

**Comment by DetachHead** [comment]
this seems to have been fixed upstream
