### ISSUE TITLE
reportDeprecated not behaving according to PEP 585 recommendation

### ISSUE THREAD

**Issue by alydh-annotell** [DetachHead/basedpyright#213]
Setting the diagnostics override for `reportDeprecated` still report diagnostics

Using the following config for neovim
![2024-03-26T15-17-28](https://github.com/DetachHead/basedpyright/assets/65158011/b802a852-9ff0-4eef-a6d0-70ac6e0d25e9)

Which results in the following diagnostics message in the editor. 

![2024-03-26T15-14-44](https://github.com/DetachHead/basedpyright/assets/65158011/3fe780fc-b896-4d00-8b2d-e849520dd8da)

My interpretation of the following sentence from PEP 585 is that the config override should silence the diagnostics message

> It’s recommended to allow for those warnings to be silenced on a project-wide basis.

[Referenced chapter in PEP](https://peps.python.org/pep-0585/#implementation)

I'm not at all familiar with the implementation, but this suggests that the diagnostics is added even if the override is set to "none"
https://github.com/DetachHead/basedpyright/blob/67935cac4a0437a70e0bb7bcacaa45c97398ecb0/packages/pyright-internal/src/analyzer/checker.ts#L4270-L4278

**Comment by DetachHead** [comment]
same issue as #149

it's because pyright by default reports deprecations, unused and unreachable diagnostics with their own categories that can't be suppressed, instead of error/warning

closing in favor of #149
