### ISSUE TITLE
`reportUnnecessaryComparison` does not take non-overlapping type parameters into account

### ISSUE THREAD

**Issue by DetachHead** [DetachHead/basedpyright#259]
```py
def asdf(a: list[int], b: list[str]):
    if a == b: # no error
        ...
```
[playground](https://pyright-play.net/?strict=true&deprecateTypingAliases=true&enableExperimentalFeatures=true&reportCallInDefaultInitializer=true&reportImplicitStringConcatenation=true&reportImplicitOverride=true&reportMissingSuperCall=true&reportPropertyTypeMismatch=true&reportShadowedImports=true&reportUnnecessaryTypeIgnoreComment=true&reportUninitializedInstanceVariable=true&code=CYUwZgBAhgzsYAooC4IBsCWMAuBtDAdtgLoA0EARqpjrjgE7ECUyAsAFARcQaRQQBeAZTadu4gHRSgA)

rejected upstream issue: https://github.com/microsoft/pyright/issues/7624

**Comment by DetachHead** [comment]
actually this behavior is correct, because if both values were empty lists the condition would return `True`

**Comment by KotlinIsland** [comment]
if you ask me, this is very similar to:
- https://github.com/KotlinIsland/basedmypy/issues/676

i would prefer it imo

**Comment by DetachHead** [comment]
[that works in basedpyright](https://basedpyright.com/?typeCheckingMode=all&code=CYUwZgBA%2BgFAhgLggSwHYBcIB8IDkD2qIANBAEZIDO6ATtnoSAJQIBQEHKkcEAvL%2BSQQAxBFT4IIGjXw12nBQDplQA)
