### ISSUE TITLE
Add typemod for decorators

### ISSUE THREAD

**Issue by johannesrld** [DetachHead/basedpyright#278]
Currently, `lsp.type.decorator` can be overwritten by a couple lsp tokens, for example `@classmethod` is overwritten by:

- `lsp.type.class` 
- `lsp.mod.builtin`
- `lsp.mod.defaultLibrary`
- `lsp.typemod.class.builtin`
- `lsp.typemod.class.defaultLibrary`

it would be nice to have something like `lsp.mod.decorator`, `lsp.typemod.decorator.builtin` or `lsp.typemod.decorator.defaultLibrary` so we can highlight decorators with the same colour regardless of if they're classes or functions

**Comment by DetachHead** [comment]
is `mod` and `typemod` a neovim-specific thing? i see it's [mentioned here](https://neovim.io/doc/user/lsp.html#lsp-semantic-highlight) but i can't find anything about it in [the LSP spec](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/)

happy to support it, tho i find it weird that semantic tokens are different in each editor

**Comment by RayJameson** [comment]
I'm not sure if this the right issue, but I'm using this workaround for decorator highlighting

I've added this to `basedpyright` lsp configuration
```lua
        on_attach = function()
          vim.api.nvim_create_autocmd("LspTokenUpdate", {
            callback = function(args)
              local token = args.data.token
              if token.type == "decorator" and not token.modifiers.readonly then
                vim.lsp.semantic_tokens.highlight_token(
                  token,
                  args.buf,
                  args.data.client_id,
                  "@lsp.type.decorator.python",
                  { priority = 130 }
                )
              end
            end,
          })
        end,
```

this is the result
![image](https://github.com/user-attachments/assets/2baab2b0-aaeb-4d9b-b570-53465d51fb39)

**Comment by RayJameson** [comment]
vscode uses same color regardless of that, I think it's something of opinionated matter, as for me, I would like to see one color for all parts, since decorators are always callables and there shouldn't be misunderstanding because module part is not colored differently

**Comment by RayJameson** [comment]
And yes, your assumption is correct, here is a screenshot of inspect command (shows applied highlighting stuff)
As you can see both decorator and function have priority 125
![image](https://github.com/user-attachments/assets/c4abaf54-1a0c-46ba-a903-5764900f3783)

**Comment by DetachHead** [comment]
> vscode uses same color regardless of that (in pylance), I think it's something of opinionated matter, as for me

as far as i can tell pylance doesn't use the `decorator` token type at all and just uses the token types of the individual symbol(s) that make up the decorator

> I would like to see one color for all parts, since decorators are always callables and there shouldn't be misunderstanding if module part is not colored differently, also I like how it looks visually, 3 different colors looks ugly for single (kinda) symbol to me

my concern is that since decorators can be any expression, it seems like a bad idea to highlight every symbol inside the expression as such regardless of whether the individual symbol itself is a decorator. another example off the top of my head is functions that take an argument and return a decorator, eg:

```py
class Foo:
    @foo(bar) # should "bar" be highlighted as a decorator as well?
    def a(self): ...
```

but anything can be a decorator:
```py
class Foo:
    @baz(qux).asdf[a + b]() # should all of these symbols be highlighted as decorators?
    def b(self): ...
```

**Comment by RayJameson** [comment]
that's a great point, I didn't think about it. I believe in those cases falling back is the right move and actually it doesn't look as bad as I thought
![image](https://github.com/user-attachments/assets/4d2045ee-01ea-4143-96d3-98e7ffeadd62)

**Comment by RayJameson** [comment]
not that johannesrld said it I think it might be a better approach 🙂

**Comment by DetachHead** [comment]
thanks for the input guys, though i still think my idea to only do it on simple decorators like `@foo` makes the most sense. it's also less risky as it's less likely for parts of the expression to be incorrectly highlighted due to decorator expressions that i didn't account for
