### ISSUE TITLE
Markdown badge

### ISSUE THREAD

**Issue by jorenham** [DetachHead/basedpyright#279]
I've recently switched from pyright to basedpyright in [optype](https://github.com/jorenham/optype), and I'm quite happy about it. The only thing that's still missing, is a "basedpyright" badge that I can use instead of the "pyright" one from the [pyright docs](https://microsoft.github.io/pyright/#/ci-integration?id=adding-pyright-badge-to-readmemd).

The first ones that came to mind are:

![image](https://github.com/DetachHead/basedpyright/assets/6208662/f2084147-7218-42c5-8347-5da2bfd3fef0)
![image](https://github.com/DetachHead/basedpyright/assets/6208662/9e095b67-2770-4fa5-8f48-dee34158f64b)

![image](https://github.com/DetachHead/basedpyright/assets/6208662/29951ec1-b701-4587-8e5f-c591afc5d602)
![image](https://github.com/DetachHead/basedpyright/assets/6208662/c7a6e44a-f94e-40af-8f55-61577a819be6)

(from https://michaelcurrin.github.io/badge-generator/#/generic)

**Comment by DetachHead** [comment]
![image](https://github.com/DetachHead/basedpyright/assets/6208662/29951ec1-b701-4587-8e5f-c591afc5d602) looks good. just curious what colour did you use exactly?

**Comment by jorenham** [comment]
I took the hex color code from the color of the `<a>` in the docs, `#42b983`
