### ISSUE TITLE
Inlay hints for inferred generics

### ISSUE THREAD

**Issue by KotlinIsland** [DetachHead/basedpyright#296]
```py
@dataclass
class A[T]:
    t: T
print(A(1))
```
The inlay should show on the line:
```py
print(A`[int]`(1))
```

And functions:
```py
def f[T](t: T): ...
f`[int]`(1)  # WARNING: this isn't valid denotation!!!
```

Not sure how collection literals would look:
```py
print(`[int]`[1, 2, 3])
print(`[int]`{1, 2, 3})
print(`[int]`{1, 2, 3})
```
Additionally, this is invalid syntax.

**Comment by DetachHead** [comment]
i think they should only appear in instances where it's valid (ie. only on classes, not functions or literals)

**Comment by DetachHead** [comment]
hmm, looks like inlay hints for other languages don't follow my made-up rule: https://code.visualstudio.com/docs/typescript/typescript-editing#_inlay-hints

specifically, these inlay hints would not be valid syntax if they were to be converted to real code:

![inlay-parameters](https://github.com/DetachHead/basedpyright/assets/57028336/d98c6ec0-d711-4c54-876b-72485a5bd2a8)

so i might change my mind about this, but we need to keep #198 in mind

**Comment by DetachHead** [comment]
#818
