### ISSUE TITLE
`reportPrivateLocalImportUsage` is an unknown config option

### ISSUE THREAD

**Issue by amitkparekh** [DetachHead/basedpyright#300]
Hi! I'm trying to disable `reportPrivateLocalImportUsage` rule but the basedpyright vscode extension says the following: 

> `[Error - 17:44:48] unknown config option: reportPrivateLocalImportUsage`

I noticed that there's an inconsistency in the naming for this rule? The [README](https://github.com/DetachHead/basedpyright?tab=readme-ov-file#reportprivatelocalimportusage---prevent-implicit-re-exports-in-local-code) says `reportPrivateLocalImportUsage` but the  [docs/configuration.md](https://github.com/DetachHead/basedpyright/blob/main/docs/configuration.md#based-options) calls it `reportAllPrivateImportUsage`. I did a search in the repo and it seems that `reportAllPrivateImportUsage` is only see in the `configuration.md` file so I'm assuming it's just a typo that fell through the cracks! 

I've tried both config options and apparently neither are known. I had a look at the playground and neither are listed there either (screenshotted below) so maybe that helps with figuring out why it's not showing up! 

![CleanShot 2024-04-16 at 17 54 12](https://github.com/DetachHead/basedpyright/assets/7276308/bd6d0bec-3c90-4f8e-a403-0bcd9ab96304)

Let me know if I can help further!

**Comment by DetachHead** [comment]
will be fixed in the next release, sorry about that!

regarding the playground, the list of settings for it [are maintained separately](https://github.com/DetachHead/basedpyright-playground/blob/main/client/PyrightConfigSettings.ts) for some reason, and i just never bothered adding this rule because the playground doesn't support multiple files anyway

**Comment by amitkparekh** [comment]
Thank you for fixing this so quickly!! I'm really enjoying using basedpyright over mypy/pylance since it's just so much faster and I can't wait for basedmypy to be integrated into basedpyright fully!

**Comment by DetachHead** [comment]
thanks for the kind words! feel free to raise/upvote issues under the https://github.com/DetachHead/basedpyright/labels/basedmypy%20feature%20parity label for specific things you want, it helps us prioritize features people want the most.

**Comment by BarrensZeppelin** [comment]
`reportImplicitRelativeImport` is also an unknown config option. :slightly_smiling_face:

**Comment by DetachHead** [comment]
thanks, fixed in #306
