### ISSUE TITLE
`type_check_only` should be banned at runtime

### ISSUE THREAD

**Issue by KotlinIsland** [DetachHead/basedpyright#305]
```py
function  # "function" is marked as @type_check_only and can be used only in type annotations"
a: function
```
[pep says](https://peps.python.org/pep-0484/#:~:text=%40-,type_check_only,-%2C%20a%20decorator%20only) that it shouldn't be available at runtime (and this makes sense imo).

The error currently says it's only allowed in annotations, but, erm, annotations are evaluated at runtime, soooo.

**Comment by DetachHead** [comment]
Duplicate of #276
