### ISSUE TITLE
provide a thingy

### ISSUE THREAD

**Issue by KotlinIsland** [DetachHead/basedpyright#312]
bpr:
![image](https://github.com/DetachHead/basedpyright/assets/65446343/4084720a-0063-455f-ade7-fd6c6ad70c20)

pylance:
![image](https://github.com/DetachHead/basedpyright/assets/65446343/ff853f8c-64c9-4a09-9758-5f7edb0156f7)

Is this LSP or VSC?

**Comment by DetachHead** [comment]
i want to discourage changing type checking settings in the vscode setting (you should pretty much always do it in `pyproject.toml` instead) so i won't add the type checking mode one. 

as for the import completions, is that something you'd want to toggle often enough that it needs to be accessible from that toolbar thing?

**Comment by KotlinIsland** [comment]
Your correct, is there anything that we would want to provide via the thingy?

**Comment by DetachHead** [comment]
i dont think so. can re-open if anybody thinks of something useful to put there
