### ISSUE TITLE
pip install basedpyright not installing the latest version?

### ISSUE THREAD

**Issue by leet0rz** [DetachHead/basedpyright#338]
As far as I can see in the releases the latest version is 1.11.0, on pypi it is also basedpyright 1.11.0. On the same page (pypi), there is a command to install it with `pip install basedpyright` but it installs 1.6.1 for me. I would assume it should be installing 1.11.0?

**Comment by KotlinIsland** [comment]
What operating system and python version are you using?

**Comment by leet0rz** [comment]
> What operating system and python version are you using?

Windows 10, python 3.12.

**Comment by KotlinIsland** [comment]
Could you please also capture the full output of `pip install basedpyright --verbose` (when it isn't installed yet)

**Comment by leet0rz** [comment]
> Could you please also capture the full output of `pip install basedpyright --verbose` (when it isn't installed yet)

That actually fixed it, uninstalling it and installing it again now provides the right version. Thanks. When I was trying to upgrade or anything like that it would say it satisfied the latest version. Weird.

**Comment by DetachHead** [comment]
in that case i'll assume this was an issue with pip and close this issue. feel free to raise another issue if it keeps happening (or just comment here and i'll reopen it)

btw i recommend [pdm](https://github.com/pdm-project/pdm), it's much better than pip

**Comment by KotlinIsland** [comment]
Maybe `pip install basedpyright --upgrade` was needed
