### ISSUE TITLE
`reportDeprecated` confused by aliasing

### ISSUE THREAD

**Issue by AlexBlandin** [DetachHead/basedpyright#346]
Version: BasedPyright v1.12.0

```
This type is deprecated as of Python 3.9; use "collections.abc.Set" instead
```
> `basedpyright(reportDeprecated)`

As seen below, the snippet `foo` has this error on `AbstractSet`

Following the advice/fix from Ruff:
```
Use `from collections.abc import Set as AbstractSet` to avoid confusion with the `set` builtin
```
> `Ruff(PYI025)`

We have (aliased) `collections.abc.AbstractSet` as opposed to `typing.AbstractSet`, so the deprecation check should not have passed.

This pattern is used in `typeshed-fallback`, and more pervasively on `.pyi` files.

The `bar` snippet demonstrates the deprecation check not passing on a different alias of `Set`.

This may simply be a limitation in the parsing; as gathered from `deprecatedSymbols.ts`, which exposes `fullName` but might not check against it.

It also seems related to #89 though presumably the fix applied there has not impacted this aliasing issue.

```python

from collections.abc import Set as AbstractSet


def foo(a: AbstractSet[str]):
  pass

```

```python

from collections.abc import Set as AbSet


def bar(a: AbSet[str]):
  pass

```

**Comment by DetachHead** [comment]
this has been fixed upstream: https://github.com/microsoft/pyright/issues/7875#issuecomment-2111592430
