### ISSUE TITLE
positional-only arguments should not have inlay hints

### ISSUE THREAD

**Issue by DetachHead** [DetachHead/basedpyright#361]
```py
def foo(value: int, /) -> None: ...

foo(1)
```
![image](https://github.com/DetachHead/basedpyright/assets/57028336/0db4aac6-2ad4-4beb-b5ca-3e3cb6bc1988)

**Comment by DetachHead** [comment]
lol this is what it does in pylance

![image](https://github.com/DetachHead/basedpyright/assets/57028336/cb31e7da-df11-4ab0-9012-f8baec1886be)

**Comment by KotlinIsland** [comment]
"ignoring keyword only", i would be very amused to see an inlay hint on a keyword only argument...
