### ISSUE TITLE
`type: ignore` comment must specify a rule (eg. `# type: ignore[ruleName]`) does not play nice with mypy

### ISSUE THREAD

**Issue by ColinKennedy** [DetachHead/basedpyright#374]
I have code like this

```python
with self.assertRaises(ValueError):
    foo.Bar()
```

It errors in `mypy` as expected because it's part of a unittest where it needs to fail.

`No overload variant of "Bar" matches argument type ...`

Since I need to ignore all issues, I add `# type: ignore` as directed by most Internet suggestions (e.g. https://stackoverflow.com/a/49220098/3626104)

```python
with self.assertRaises(ValueError):
    foo.Bar()  # type: ignore
```

When I do this, basedpyright errors with `type: ignore` comment must specify a rule (eg. `# type: ignore[ruleName]`). This is bad because 

1. This suggestion is incompatible with mypy and fails CI. If I changed `foo.Bar()  # type: ignore` to `foo.Bar()  # type: ignore[errors]` or some other comment, `mypy --strict` now errors with `Unused "type: ignore" comment  [unused-ignore]`
2. It doesn't specify what rule, if any, it wants me to use

The best I can do in this scenario is to explicitly tell mypy to ignore unused ignores but I haven't actually tried to see if that works yet. Overall pretty frustrating that an IDE feature is not inline with the CI.

Is there a way to disable just this check? I like all/most of the other basedpyright checks, just not this one.

**Comment by DetachHead** [comment]
i recommend disabling `enableTypeIgnoreComments` to prevent basedpyright from looking at them (this will soon be the default behavior)

https://github.com/DetachHead/basedpyright/issues/330#issuecomment-2084382899

**Comment by ColinKennedy** [comment]
Is there a way to specify `enableTypeIgnoreComments` via the usual LSP client settings? For example at the moment I'm doing

```lua
lspconfig.basedpyright.setup {
    capabilities = require("cmp_nvim_lsp").default_capabilities(),
    on_attach = on_attach,
    settings = {
        basedpyright = {
            analysis = { diagnosticMode = "off", typeCheckingMode = "off" },
        }
    }
}
```

Which maps to `basedpyright.analysis.diagnosticMode` and `basedpyright.analysis.typeCheckingMode` from https://docs.basedpyright.com/#/settings?id=pyright-settings

I & my company generally don't use use pyproject.toml files files (which I'm assuming is what your example text is from) and discourage text-editor-centric code in repositories. So instead I adjust LSP capabilities from the client (in this case, Neovim).


Other question if you don't mind, I did try to have both at once 

`MYPYPATH=/path/to/my/stubs nvim some_file.py`
+ 
`analysis = { stubPath = "/path/to/my/stubs" },`

mypy reports no errors with the above but basedpyright still errors saying things like `Type of "Bar" is unknown`. I was wondering if I was using the wrong setting.

**Comment by DetachHead** [comment]
> Is there a way to specify `enableTypeIgnoreComments` via the usual LSP client settings? For example at the moment I'm doing
> 
> ```lua
> lspconfig.basedpyright.setup {
>     capabilities = require("cmp_nvim_lsp").default_capabilities(),
>     on_attach = on_attach,
>     settings = {
>         basedpyright = {
>             analysis = { diagnosticMode = "off", typeCheckingMode = "off" },
>         }
>     }
> }
> ```
> 
> Which maps to `basedpyright.analysis.diagnosticMode` and `basedpyright.analysis.typeCheckingMode` from https://docs.basedpyright.com/#/settings?id=pyright-settings

does this work?
```lua
lspconfig.basedpyright.setup {
    capabilities = require("cmp_nvim_lsp").default_capabilities(),
    on_attach = on_attach,
    settings = {
        basedpyright = {
            analysis = { typeCheckingMode = "off", enableTypeIgnoreComments = false },
        }
    }
}
```

> Other question if you don't mind, I did try to have both at once
> 
> `MYPYPATH=/path/to/my/stubs nvim some_file.py` + `analysis = { stubPath = "/path/to/my/stubs", typeCheckingMode = "off" },`
> 
> mypy reports no errors with the above but basedpyright still errors saying things like `Type of "Bar" is unknown`. I was wondering if I was using the wrong setting.

you'll still need to disable type checking if you don't want any errors from basedpyright:
```lua
analysis = { stubPath = "/path/to/my/stubs", typeCheckingMode = "off" }
```

**Comment by ColinKennedy** [comment]
I can confirm that `analysis = { stubPath = "/path/to/my/stubs", typeCheckingMode = "off" }` works. `goto definition` jumps to the stub file as intended and `find references` can be used on a stubbed class and it finds all instances as expected. And the type-related diagnostics are disabled, nice!

Unfortunately though, it looks like with the above setting, I still get diagnostics such as `basedpyright: Result of call expression is of type "str" and is not used; assign to variable "_" if this is intentional [reportUnusedCallResult]` on lines like 

```python
bar.get_label()  # noqa
```

Since basedpyright doesn't respect noqa or a similar tag, it still shows an error even if I want to explicitly ignore it. So I think the final configuration I would need to settle on is `analysis = { typeCheckingMode = "off", stubPath = "/path/to/my/stubs}`. No big deal though, I still have pylint, mypy, and friends to fall back on.

Thank you for your help!

**Comment by DetachHead** [comment]
oh, i think i misunderstood your question. you can disable specific rules if you like, while keeping everything else enabled:

```lua
analysis = { stubPath = "/path/to/my/stubs", reportUnusedCallResult = "off" }
```
