### ISSUE TITLE
Support inferring `@final` `TypedDict`s to be `Mapping[str, Union | Of | Types]`

### ISSUE THREAD

**Issue by DetachHead** [DetachHead/basedpyright#385]
original issue: https://github.com/microsoft/pyright/issues/3526
> **Is your feature request related to a problem? Please describe.**
> 
> ```python
> from __future__ import annotations
> from typing import Mapping, TypedDict, final
> 
> FileTypes = bytes
> 
> # this has to be key agnostic
> RequestFiles = Mapping[str, FileTypes]
> 
> def post(files: RequestFiles | None = None):
>     ...
> 
> @final
> class FileParams(TypedDict):
>     file: FileTypes
> 
> def foo(files: FileParams):
>     # error: Argument of type "FileParams" cannot be assigned to parameter "files" of type "RequestFiles | None" in function "post"
>     post(files)
> ```
> 
> **Describe the solution you'd like**
> 
> Ideally pyright could infer that the `FileParams` TypedDict could be safely passed to the `post` function as it is known to only contain keys with the type `FileTypes` and cannot be subclassed to add more keys because it is decorated with `@final`.
> 
> **Additional context**
> 
> I apologise if there's prior discussion surrounding this, I couldn't find any.

**Comment by DetachHead** [comment]
this should also ideally work with pyright's experimental inline `TypedDict` syntax:

```py
foo: dict[{"foo": int}]
```

perhaps by reusing `typing.Final` for this purpose:

```py
foo: Final[dict[{"foo": int}]]
```

**Comment by DetachHead** [comment]
using `@final` probably isnt the best solution here since `TypedDict`s are structural (#621). we should probably instead wait until https://peps.python.org/pep-0728/

**Comment by KotlinIsland** [comment]
> `Mapping[str, Union | Of | Types]`
I can only assume that `Union` here means `typing<_extensions>.Union`, but it would be invalid to use it like this. Are you suggesting new syntax for `Union`?

additionally, it is invalid to use the types `Of` and `Types` without specifying what they are defined on

**Comment by DetachHead** [comment]
pyright now supports closed typed dicts, the example in the OP works when you define `FileParams` with `closed=True`.

Code sample in [basedpyright playground](https://basedpyright.com/?typeCheckingMode=all&reportUnnecessaryIsInstance=true&reportUnreachable=true&reportUnusedParameter=false&reportDeprecated=false&code=GYJw9gtgBA%2BjwFcAuCQFM5QJYQA5hCSgEMA7UsJYpLMUgZwChRIokBPXLUgc2zwJEAssVxdeAGigAVTmgAmAESwBjJFODdiAG0aMAYlm1pZuNPSgBeKACN2Sc3oDEbABZYLr4haRhbaKABrNHYSHgp6GhVGACU0AEcEcyRDYwtrETFuHgBtSJApVJM5egBdPXk0YCh8SIAKTTSALig4xOSiiwAfKAA5OgDrftI0AEomxigpqAA6Ob0AAU1SHUYVbW8LIoAFYhBiCHo60wVlNSl1sHoFS2kQJPHJ6ca0FqKTpkZK6uAwMAajOY3oDdvtDo9plAXBQoBACAE0CBwCAnlNakgAWlRkA)

```python
from __future__ import annotations
from typing import Mapping, TypedDict, final

FileTypes = bytes

# this has to be key agnostic
RequestFiles = Mapping[str, FileTypes]

def post(files: RequestFiles | None = None):
    ...

@final
class FileParams(TypedDict, closed=True):
    file: FileTypes

def foo(files: FileParams):
    # no more error
    post(files)
```
