### ISSUE TITLE
Don't collapse `str` and `Literal["some string"]` to preserve auto complete suggestions

### ISSUE THREAD

**Issue by KotlinIsland** [DetachHead/basedpyright#397]
![image](https://github.com/DetachHead/basedpyright/assets/65446343/4d9705b5-0d7e-45ff-a1dd-fb059b9bb431)
![image](https://github.com/DetachHead/basedpyright/assets/65446343/9bd720d3-dff1-4b87-9f1c-296c39836252)

**Comment by DetachHead** [comment]
Duplicate of #320
