### ISSUE TITLE
Variables narrowed to Never with an explicit type are highlighted as types

### ISSUE THREAD

**Issue by ValdezFOmar** [DetachHead/basedpyright#398]
Now is the opposite of https://github.com/DetachHead/basedpyright/issues/254

![image](https://github.com/DetachHead/basedpyright/assets/80359343/a9dfd3d5-95e5-4e5f-94d0-e0e95ca53bf5)

**Comment by DetachHead** [comment]
man i swear i had a test for this...

not sure how to fix it because as far as i can tell theres no easy way to differentiate between an instance of `Never` and the `Never` type itself :(

**Comment by ValdezFOmar** [comment]
I will take a look at it and see if I can do something.

**Comment by DetachHead** [comment]
i think i got it in #398
