### ISSUE TITLE
non-literal iterators should be able to indicate that they will run at least once

### ISSUE THREAD

**Issue by KotlinIsland** [DetachHead/basedpyright#407]
# Problem:
```py
for _ in range(1):
    a = 1
print(a)  # error: possibly undefined
```

# Solution:
```py
x: int
y: int
for _ in range(x, y) or (1,):
    a = 1
print(a)  # ah yes, it's defined
```

a `once` helper would be useful:
it would assert that it runs at least once
```py
x: int
y: int
for _ in once(range(x, y)):
    a = 1
print(a)  # ah yes, it's defined
```

Although, this could be addressed at a fundamental level.

**Comment by DetachHead** [comment]
Duplicate of #348

**Comment by DetachHead** [comment]
actually no its not, thats related to literals which is probably easier to do than this

**Comment by DetachHead** [comment]
actually i changed my mind i think these should both be addressed as part of the same issue
