### ISSUE TITLE
Make sure the licence is golden

### ISSUE THREAD

**Issue by KotlinIsland** [DetachHead/basedpyright#41]

**Comment by DetachHead** [comment]
it's MIT so i'm pretty sure it's fine

**Comment by DetachHead** [comment]
i was under the impression that you're supposed to just keep the license as-is when forking a project, and any changes would need approval from everybody who has ever contributed to the project, but @decorator-factory pointed out that this isn't exactly true:

> <https://opensource.stackexchange.com/a/7917>
> it could be changed to something like  
> ```
> MIT License
> 
> Basedpyright
> Copyright (c) Basedpyright maintainers
> 
> Basedpyright is a fork of Pyright, created by Microsoft Corporation and licensed under the MIT license.
> Pyright - A static type checker for the Python language
> Copyright (c) Microsoft Corporation. All rights reserved.
> 
> ..<rest of the file>
> ```

> A fork is just a specific kind of a derivative work. Essentially, you're using code provided by Microsoft in your own work. So you have to follow the terms of the license: namely, retain the text of the license and make it clear which parts you borrowed

> I think ...something needs to change, because we don't want to misrepresent this as being a Microsoft product

re-opening this for further investigation

**Comment by decorator-factory** [comment]
IANAL btw
