### ISSUE TITLE
`basedpyright.analysis.diagnosticSeverityOverrides` does not work in vscode's `settings.json`

### ISSUE THREAD

**Issue by DetachHead** [DetachHead/basedpyright#418]
upstream issue in pyright. works fine in pylance

```json
{
  "basedpyright.analysis.diagnosticSeverityOverrides": {
    "reportAttributeAccessIssue":false,
    "reportUnusedVariable": false,
    "reportDeprecated": false
  },
}
```
```py
foo = 1
foo.asdfasdf # error: reportAttributeAccessIssue
```

**Comment by willofferfit** [comment]
If it's an upstream issue, was an issue already opened in https://github.com/microsoft/pyright/ to report this?

**Comment by DetachHead** [comment]
feel free to raise it yourself if you want. i stopped raising issues upstream after receiving [this response](https://github.com/microsoft/pyright/issues/8065#issuecomment-2146352290)

**Comment by willofferfit** [comment]
Wow I'd have stopped too. Do you have more details about the bug that I could include in the bug report?

**Comment by andryandrew** [comment]
This seems relevant: https://github.com/DetachHead/basedpyright/issues/387

**Comment by DetachHead** [comment]
upstream the setting is called `python.analysis.diagnosticSeverityOverrides` and it only happens on the pyright vscode extension, but not pylance. i think it may be a regression from a recent release but i don't know for sure.

**Comment by DetachHead** [comment]
Duplicate of #387
