### ISSUE TITLE
Add lsp-bridge in basedpyright docs

### ISSUE THREAD

**Issue by manateelazycat** [DetachHead/basedpyright#476]
Hi, I'm author of [lsp-bridge](https://github.com/manateelazycat/lsp-bridge)

I just push a commit that make basedpyright as default Python LSP server: https://github.com/manateelazycat/lsp-bridge/commit/19060bd4e9911fa0e8a1a59c55fdc9eaa8407b36

Can you add lsp-bridge in https://docs.basedpyright.com/#/installation?id=emacs ? 

Thanks for great work on basedpyright. ;)

**Comment by DetachHead** [comment]
i'm not familiar with emacs, so do you mind creating a PR adding the necessary setup instructions? the installation docs are located [here](https://github.com/DetachHead/basedpyright/blob/main/docs/installation.md)

**Comment by manateelazycat** [comment]
@DetachHead https://github.com/DetachHead/basedpyright/pull/479

Thanks.
