### ISSUE TITLE
Support for awaiting "Future like" objects

### ISSUE THREAD

**Issue by jcorbett-sweater** [DetachHead/basedpyright#486]
Objects with a __await__ method are awaitable "Future like" objects according to [PEP-0492](https://peps.python.org/pep-0492/)

currently basedpyright doesn't recognize a method that returns a "future like" object as awaitable and generates an error saying the object is not awaitable.  An example of the objects in the [beanie](https://beanie-odm.dev) project.

**Comment by jcorbett-sweater** [comment]
Sure, I'll get a simple code sample together.  It may take me a few days.

**Comment by KotlinIsland** [comment]
@jcorbett-sweater i'm going to close this issue at this time, but feel free to comment and we can reopen, or raise a new issue if you'd like 🙂
