### ISSUE TITLE
Docs: do we keep up with upstream

### ISSUE THREAD

**Issue by SichangHe** [DetachHead/basedpyright#497]
Hello there! It seems BasedPyright does port changes from upstream, but I cannot see it mentioned anywhere.

Is that the case? If so, it would be nice to highlight that in the docs so people are less hesitant to try BasedPyright out.

Thanks,\
Steven Hé (Sīchàng)

**Comment by DetachHead** [comment]
we merge every upstream pyright release into basedpyright, and [each release](https://github.com/DetachHead/basedpyright/releases) includes the pyright version number, as well as the output of `basedpyright --version`:

```
> basedpyright --version
basedpyright 1.13.3
based on pyright 1.1.371
```

but yeah i agree this should probably be documented somewhere
