### ISSUE TITLE
Overridden inner class reported as error

### ISSUE THREAD

**Issue by rnovacek** [DetachHead/basedpyright#502]
This code:

```
class Base:
    class Meta:
        document: str


class Inherited(Base):
    class Meta:
        document = 'inherited'
```

Fails the type check with following error:

```
/home/radek/tmp/test.py
  /home/radek/tmp/test.py:7:11 - error: "Meta" overrides symbol of same name in class "Base"
    "test.Inherited.Meta" is incompatible with "test.Base.Meta"
    Type "type[test.Inherited.Meta]" is incompatible with type "type[test.Base.Meta]" (reportIncompatibleVariableOverride)
1 error, 0 warnings, 0 notes
```

I don't think this should be an error as the type of inherited `Meta` matches the base `Meta`.

This is a common pattern for example in [Django ORM](https://docs.djangoproject.com/en/5.0/ref/models/options/).

**Comment by rnovacek** [comment]
Workaround is to specify the inner class from parent as a base:

```
class Inherited(Base):
    class Meta(Base.Meta):
        document = 'inherited'
```

No errors like this.

**Comment by DetachHead** [comment]
sounds like the error is correct here, because in your first example `Inherited.Meta` is not a subclass of `Base.Meta`, so pyright sees them as completely unrelated types.

another option is to use a `Protocol` for the base class to make the `Meta` class structural instead of nominal:

```py
from typing import Protocol

class Base:
    class Meta(Protocol):
        document: str


class Inherited(Base):
    class Meta:
        document = 'inherited' # no error
```

**Comment by rnovacek** [comment]
Ah, ok, your explanation makes sense. The `Protocol` solution is nice, but the Base class usually comes from external library. I'll go with the `Base.Meta` parent class.

Feel free to close this issue.
