### ISSUE TITLE
Options to disable each type of inlay hint

### ISSUE THREAD

**Issue by decorator-factory** [DetachHead/basedpyright#542]
Inlay hints can be useful, but sometimes they aren't. I personally find these keyword argument hints annoying:
![image](https://github.com/user-attachments/assets/75ab44c1-d516-4919-89bf-016a6354ad16) 
Pylance has the ability to turn off specific inlay hint types, I think it would be great to port that to basedpyright.

**Comment by fny** [comment]
As a simpler first step, disabling inlay hints altogether would be a welcome addition.

**Comment by DetachHead** [comment]
you should be able to do that already, which editor are you using?

**Comment by fny** [comment]
It would be nice if this were mentioned somewhere docs on the configuration page. It's the first time I've seen them appear by default on any VS Code extension, and I had no idea how to disable it.
