### ISSUE TITLE
Throwing error for non existence of an attribute when it actually exists and works 

### ISSUE THREAD

**Issue by tahseenjamal** [DetachHead/basedpyright#543]
Masonite Framework for Python

using 
```request.session.set(key, value) ```

error by basedpyright is
```cannot access attribute "session" for class Request```

But that is incorrect as it works

**Comment by KotlinIsland** [comment]
Could you please provide a more comprehensive example, it's quite difficult to see what is happening here.

**Comment by KotlinIsland** [comment]
Given what I can find: https://github.com/MasoniteFramework/masonite/blob/4.0/src/masonite/request/request.py

I can't see any reference to a `session` attribute

**Comment by tahseenjamal** [comment]
This code works
```request.session.set``` 
also works


The below code works. 


```
class VerificationController(Controller):

    def email(self, view: View):
        return view.render("register_email")

    def submit(self, request: Request, response: Response, mail: Mail):
        otp = random.randint(1000, 9999)
        email = request.input("email")

        request.session.set("otp", otp)  # type: ignore

        message_data = SendOTP(email, otp)

        mail.mailable(message_data).send()

        return response.redirect(name="verify")

    def verify(self, view: View):
        return view.render("verify_otp")

    def check(self, request: Request, response: Response):
        otp = request.session.get("otp")  # type: ignore
        user_otp = request.input("otp")

        if otp == int(user_otp):
            return response.redirect(name="success")

        return "Invalid OTP"

    def success(self):
        return "Success"
```

**Comment by tahseenjamal** [comment]
> Given what I can find: https://github.com/MasoniteFramework/masonite/blob/4.0/src/masonite/request/request.py
> 
> I can't see any reference to a `session` attribute

You cannot see that is because session is injected by middleware and not a part of Request as static or class method

**Comment by DetachHead** [comment]
> You cannot see that is because session is injected by middleware and not a part of Request as static or class method

is that something that masonite does? if so it sounds like an issue with masonite's types, and i would recommend raising an issue there instead

if you still think this is an issue with (based)pyright, would you be able to please provide a minimal example, including what you're importing from masonite? if you could remove the need to install masonite for me to investigate this it would be super helpful, since i can't seem to get masonite to install on my PC (it tries and fails to build a wheel for one of its dependencies)

**Comment by tahseenjamal** [comment]
I think I should import session as dependency injection instead of directly using it as ```request.session```

Then basedpyright would not raise error as then it won't be a dynamic type check

**Comment by DetachHead** [comment]
i'm not familiar with masonite but skimming through [its documentation](https://docs.masoniteproject.com/the-basics/controllers#dependency-injection) leads me to believe that's the correct solution, so i'll close this issue
