### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by abrarishere** [DetachHead/basedpyright#550]
installation failed when i was trying to install basedpyright. See error:

 ```   aarch64-linux-android-clang -o /data/data/com.termux/files/usr/tmp/tmpqtxc8tzc/build/nodejs-prefix/src/nodejs/out/Release/obj.target/cares/deps/cares/src/lib/ares_getsock.o ../deps/cares/src/lib/ares_getsock.c '-D_GLIBCXX_USE_CXX11_ABI=1' '-DNODE_OPENSSL_CONF_NAME=nodejs_conf' '-DNODE_OPENSSL_HAS_QUIC' '-DICU_NO_USER_DATA_OVERRIDE' '-D_DARWIN_USE_64_BIT_INODE=1' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-D_GNU_SOURCE' '-D__STDC_FORMAT_MACROS' '-DOPENSSL_NO_PINSHARED' '-DOPENSSL_THREADS' '-DCARES_STATICLIB' '-DHAVE_CONFIG_H' -I../deps/cares/include -I../deps/cares/config/linux  -pthread -Wall -Wextra -Wno-unused-parameter -g -pedantic -Wall -Wextra -Wno-unused-parameter --std=gnu11 -O3 -fno-omit-frame-pointer  -MMD -MF /data/data/com.termux/files/usr/tmp/tmpqtxc8tzc/build/nodejs-prefix/src/nodejs/out/Release/.deps//data/data/com.termux/files/usr/tmp/tmpqtxc8tzc/build/nodejs-prefix/src/nodejs/out/Release/obj.target/cares/deps/cares/src/lib/ares_getsock.o.d.raw   -c                                       ../deps/cares/src/lib/ares_getnameinfo.c:304:11: error: call to undeclared function 'getservbyport_r'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]                                                          304 |       if (getservbyport_r(port, proto, &se, (void *)tmpbuf, sizeof(tmpbuf),                                                   |           ^                                             ../deps/cares/src/lib/ares_getnameinfo.c:304:11: note: did you mean 'getservbyport'?                                            /data/data/com.termux/files/usr/include/netdb.h:265:27: note: 'getservbyport' declared here                                       265 | struct servent* _Nullable getservbyport(int __port_in_network_order, const char* _Nullable __proto);                          |                           ^                             1 error generated.                                              make[4]: *** [deps/cares/cares.target.mk:189: /data/data/com.termux/files/usr/tmp/tmpqtxc8tzc/build/nodejs-prefix/src/nodejs/out/Release/obj.target/cares/deps/cares/src/lib/ares_getnameinfo.o] Error 1                                                        make[4]: *** Waiting for unfinished jobs....                    make[3]: *** [Makefile:137: node] Error 2                       make[2]: *** [CMakeFiles/nodejs.dir/build.make:86: nodejs-prefix/src/nodejs-stamp/nodejs-build] Error 2                         make[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/nodejs.dir/all] Error 2                                                       make: *** [Makefile:91: all] Error 2                                                                                            *** CMake build failed                                          error: subprocess-exited-with-error                                                                                             × Building wheel for nodejs-wheel-binaries (pyproject.toml) did not run successfully.                                           │ exit code: 1                                                  ╰─> See above for output.                                                                                                       note: This error originates from a subprocess, and is likely not a problem with pip.                                            full command: /data/data/com.termux/files/usr/bin/python3.11 /data/data/com.termux/files/usr/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py build_wheel /data/data/com.termux/files/usr/tmp/tmp2jvsegik                    cwd: /data/data/com.termux/files/usr/tmp/pip-install-w856t7n9/nodejs-wheel-binaries_4c322497eaad4317af0592c586dcbcb0            Building wheel for nodejs-wheel-binaries (pyproject.toml) ... error                                                             ERROR: Failed building wheel for nodejs-wheel-binaries        Failed to build nodejs-wheel-binaries                           ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (nodejs-wheel-binaries)```

**Comment by KotlinIsland** [comment]
Can you please provide:
- what operating system you are using + version
- what version of python you are using
- what command you ran to install basedpyright

**Comment by abrarishere** [comment]
System info:
Linux localhost 4.14.180-perf+ #2 SMP PREEMPT Sat Sep 3 23:17:03 CST 2022 aarch64 Android

Android version:
11

Python info:
python -V
Python 3.11.9


I am using pip
`pip install basedpyright`

Error occurs in this process:

  `Building wheel for nodejs-wheel-binaries (pyproject.toml)`

**Comment by DetachHead** [comment]
same issue as #549 so closing this as a duplicate
