### ISSUE TITLE
LSP config doesn't accept special severities

### ISSUE THREAD

**Issue by alex007sirois** [DetachHead/basedpyright#555]
The language server configuration does not seem to accept the special severities: unused, deprecated, unreachable.
When using one such severity, it is ignored and the default severity is used.
As a workaround, setting typeCheckingMode=standard works, but also disables the strict rules (e.g. strictSetInference).

Setting the reportUnusedClass to error, warning, information or none does work, as per the documentation:
> basedpyright.analysis.diagnosticSeverityOverrides [map]: Allows a user to override the severity levels for individual diagnostic rules. "reportXXX" rules in the type check diagnostics settings in [configuration](https://docs.basedpyright.com/#/configuration?id=type-check-diagnostics-settings) are supported. Use the rule name as a key and one of "error," "warning," "information," "true," "false," or "none" as value.

Here is a minimal config from helix and a python script to test.

```toml
[language-server.basedpyright.config.basedpyright.analysis.diagnosticSeverityOverrides]
reportUnusedClass = "unused"
```

```python
class _Test: ...  # error: Class _Test is not accessed
```

My main use case for basedpyright is to use it as the best python LSP that can be used outside VSCode, reimplementing salient features from PyLance (like inlay type-hints).
The unused, deprecated and unreachable rules are more visually pleasing in an LSP context than a red error, but at the same time, I do like most rules added by typeCheckingMode=all.

For now, my workaround is using typeCheckingMode=all and using information instead of those special severities.

I use version 1.15.1 from nixos.

(BTW, thanks for the project, really appreciate the inlay type-hints in particular!)

**Comment by DetachHead** [comment]
hmm looks like the special severities only work in `pyrightconfig.json`/`pyproject.toml` but not in the lsp config. thanks for reporting this
