### ISSUE TITLE
Homebrew formula

### ISSUE THREAD

**Issue by nikaro** [DetachHead/basedpyright#556]
Hello,

Would you mind providing some guidance for building a Hombrew formula for basedpyright?

I already have one on my [personal tap](https://github.com/nikaro/homebrew-tap/blob/main/Formula/basedpyright.rb) that is working fine and i'm trying to [upstream it](https://github.com/Homebrew/homebrew-core/pull/180649). But we are wondering if there would be a way to avoid the python dependency since AFAIK the pypi package is a wrapper around the npm one? It would save up A LOT of build time.

Thank you.

**Comment by nikaro** [comment]
Solved 😅

**Comment by DetachHead** [comment]
thanks! if you'd like, feel free to also submit a PR adding it to the [installation instructions](https://github.com/DetachHead/basedpyright/blob/main/docs/installation.md)
