### ISSUE TITLE
Use of an export decorator results in imported objects of type None

### ISSUE THREAD

**Issue by ReK42** [DetachHead/basedpyright#558]
As a common pattern, I use an `@export` decorator to control which objects are added to `__all__` for the top-level module. This "brings up" submodule components and exposes them as part of the module public interface without having to understand the structure of the module code. This allows me to organize the module code without worry by simply adding `@export` to anything which should be part of the public interface and adding submodules which contain those objects to `__init__.py` with `from module.submodule import *`. This is a convenience pattern, as someone can use the full "private" interface if they choose, but it makes it very easy to explicitly define and document the "public" interface.

When doing this, basedpyright fails to understand the types of objects which have the `@export` decorator, even within the file in which they are defined. If you remove the `@export` decorator, references within the same file are correctly typed.

Here is an example screenshot of one of the errors. Notably, the hyperlinks to the class definition work and correctly bring me to line 19.

![image](https://github.com/user-attachments/assets/2d7a82a0-ecd7-4a65-84ae-c22e42c25a2c)

## Importing and Executing `test_module`
```
(.env) [~/test/src]$ python
Python 3.11.1 (tags/v3.11.1:a7a450f, Dec  6 2022, 19:58:39) [MSC v.1934 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import test_module
>>> test_module.__all__
['test_public', 'TestData', 'TestDataWrapper']
>>> test_module.test_public()
datetime.datetime(2024, 8, 10, 13, 1, 53, 786412, tzinfo=datetime.timezone.utc)
>>> test_module.test.test_public()
datetime.datetime(2024, 8, 10, 13, 1, 50, 71427, tzinfo=datetime.timezone.utc)
>>> test_module.test.test_private()
datetime.datetime(2024, 8, 10, 13, 1, 36, 494431, tzinfo=datetime.timezone.utc)
>>> ^Z

(.env) [~/test/src]$ python -m test_module
TestDataWrapper(timestamp=datetime.datetime(2024, 8, 10, 12, 27, 24, 236531, tzinfo=datetime.timezone.utc),
                data=[TestData(name='one',
                               uuid=UUID('6a97276b-1328-40ce-a586-20a3f397ade6')),
                      TestData(name='two',
                               uuid=UUID('075e377d-9aa7-4696-8081-bb14d385b813')),
                      TestData(name='three',
                               uuid=UUID('50673748-ffe6-45ac-bc6f-063c8593db98'))])
```

## Errors generated by basedpyright for `test_module`
```
~/test/src/test_module/test.py:
   27:49  error   Argument of type "None" cannot be assigned to parameter "default_factory" of type "() -> _T@field" in function "field" ​basedpyright
                    Type "None" is incompatible with type "() -> _T@field"
   27:5   error   Type of "timestamp" is partially unknown ​basedpyright
                    Type of "timestamp" is "Unknown | datetime"
   28:16  error   Expected class but received "None" ​basedpyright
   28:5   error   Type of "data" is partially unknown ​basedpyright
                    Type of "data" is "list[Unknown]"

~/test/src/test_module/__main__.py:
    9:9   error   Expected class but received "None" ​basedpyright
    9:27  error   Object of type "None" cannot be called ​basedpyright
   11:13  error   Object of type "None" cannot be called ​basedpyright
   12:13  error   Object of type "None" cannot be called ​basedpyright
   13:13  error   Object of type "None" cannot be called ​basedpyright
    9:5   error   Type of "td" is unknown ​basedpyright
   16:12  error   Argument type is unknown ​basedpyright
                    Argument corresponds to parameter "object" in function "pprint"
```

## Reproducing
I have attached a small sample module which reproduces the problem in the following environment:
* Sublime Text 4180
* LSP 2.2.0
* LSP-basedpyright 1.2.9
* Node 18.18.1
* basedpyright 1.15.1
* Python 3.11.1

[test_module.zip](https://github.com/user-attachments/files/16569628/test_module.zip)

The `@export` decorator is defined in `__init__.py`

**Comment by DetachHead** [comment]
there's currently nothing in the type system to support an `@export` decorator, but i agree it would be useful. merging this issue with #463
