### ISSUE TITLE
`reportInvalidCast` for `cast(None, object())`: "convert the expression to `object` first"

### ISSUE THREAD

**Issue by jorenham** [DetachHead/basedpyright#568]
https://basedpyright.com/?code=JYWwDg9gTgLgBDAnmYA7A5nAhgZwQKBgDoBjXGACgDkJUBTAGjggCMArOkygSm6A

So a couple of months ago I tried to do

```python
import typing as t
t.cast(None, object())
```

which gave

```
Conversion of type `object` to type `None` may be a mistake because neither type sufficiently overlaps with the other. If this was intentional, convert the expression to `object` first.  (reportInvalidCast)
```

So I decided to follow the advice, i.e.:

> convert the expression to `object` first. 

... but after I did that, it said it again. So it was obvious to me that I should keep at it for a while. 

Then after I had cast `object` to `object` for the 3000th time, my brain raised a `RecursionError`!
So now I'm wondering if maybe there's a chance that there's a bug involved here, or if I should `brain.setrecursionlimit(1 << 20)` and give it another shot 🤔. 
Any thoughts?

**Comment by DetachHead** [comment]
must be some annoying special casing with `None` causing this. thanks for reporting

**Comment by jorenham** [comment]
It's not a problem to e.g. `cast(Never, object())` or `cast(Any, object())`.

But this issue also appears to be the case for `cast(type[T], object())` with `T` e.g. `Any`, `object`, or `int`. The only except I managed to find was `cast(type[Never], object())`, which is allowed.

**Comment by jorenham** [comment]
I also found a workaround: 

```python
cast(None, cast(Never, object()))
```
