### ISSUE TITLE
name change?

### ISSUE THREAD

**Issue by DetachHead** [DetachHead/basedpyright#578]
ive seen some complaints about the name basedpyright being too "juvenile". im not too attached to it so im open to changing it if anybody can think of something better

considering just abbreviating it to "bpr". this would probably cause the least confusion so i probably wouldn't pick another name unless it was one i really like

any input from the ideas guys and logo makers out there?

**Comment by KotlinIsland** [comment]
UYou.pyright+

**Comment by jorenham** [comment]
pyleft?

**Comment by jorenham** [comment]
or perhaps "oppyright" - as in opinionated (or over-powered 😉)

**Comment by neel04** [comment]
"better-pyright" as a safe option?

**Comment by jorenham** [comment]
`right.py` 🤔

**Comment by kiyoon** [comment]
typerighter

**Comment by jorenham** [comment]
English is fun:

- pyride
- pywrite
- py[wright](https://www.merriam-webster.com/dictionary/wright)
- py[rite](https://www.merriam-webster.com/dictionary/rite)

**Comment by scott-au** [comment]
py[untitled](https://www.merriam-webster.com/dictionary/untitled#:~:text=no%20title%20or-,right,-to%20rule)
py[spruce](https://www.merriam-webster.com/dictionary/spruce#:~:text=%3A%20neat%20or%20smart%20in%20appearance%20%3A%20trim)

**Comment by jorenham** [comment]
basedonpyright 😏
