### ISSUE TITLE
Code action to suggest types from return values

### ISSUE THREAD

**Issue by FichteFoll** [DetachHead/basedpyright#580]
basedpyright provides inlay hints for return types based on the types used in `return` statements, also shown [in the inlay hints docs](https://docs.basedpyright.com/#/?id=inlay-hints). It would be nice if it also provided a code action to add these inferred types directly to the source code.

Example:

![2024-08-14_14-23-51](https://github.com/user-attachments/assets/bd24aa4a-51e8-4b70-9652-785cf4f35842)

Before:
```py
    def check_hi():
        return True, "hi"

    _ = check_hi()
```
After:
```py
    def check_hi() -> tuple[Literal[True], Literal["hi"]]:
        return True, "hi"

    _ = check_hi()
```

(The actual desired annotation here would be `tuple[bool, str]` but that doesn't matter.)

Context: SublimeText with the LSP and LSP-basedpyright packages

Related: #95
Related upstream comment and discussion: https://github.com/microsoft/pyright/issues/3013#issuecomment-1217365874

**Comment by DetachHead** [comment]
merging with #198
