### ISSUE TITLE
publish a nodeless release which would allow users on platforms other than windows/mac/linux to use a different node binary

### ISSUE THREAD

**Issue by KotlinIsland** [DetachHead/basedpyright#586]
hmm, it probably won't work with anything that expects the pypi package unfortunately.

perhaps we could also publish a nodeless release which would allow users on platforms other than windows/mac/linux to use a different node binary

_Originally posted by @DetachHead in https://github.com/DetachHead/basedpyright/issues/549#issuecomment-2283143268_

**Comment by kiyoon** [comment]
I have a coworker who still uses old Intel macOS 10. Because of this he couldn't install basedpyright. I don't know if he can use conda now that it's available though.

But I do think a nodeless package makes the availability much better.
