### ISSUE TITLE
vscode extension should depend on the `ms-python.python` extension

### ISSUE THREAD

**Issue by DetachHead** [DetachHead/basedpyright#606]
it's needed to get the python interpreter

**Comment by michaelmarziani** [comment]
Hey there @DetachHead. I was participating in a couple conversations within the issues at vscodium, as it sounds like people have noticed that your extension depends on ms-python.python, and believe this means that MS code is running, and thus all bets are off in terms of what telemetry data they can collect and send back to MS through your extension.

I'm guessing that's not true based on what I've read of this project, and perhaps this is just a way to install a python interpreter as noted here. If I may ask, is there some assurance or clarification you can give (that I'd be happy to relay) to those who want to make sure no telemetry leaves their system without their approval?

**Comment by DetachHead** [comment]
rest assured that i despise telemetry. i have never and will never use telemetry in basedpyright.

the python extension is only listed as a dependency so that basedpyright can figure out which python interpreter to use for the `python.pythonPath` setting. but i guess i should make this dependency optional for people who don't want to install any microsoft extensions at all. i opened #1147 to track this

**Comment by michaelmarziani** [comment]
Hey there @DetachHead,

I'm happy to hear your perspective, and I'll pass it on back to the other threads. Even beyond that I think making it optional would be amazing, as I think it's amazing to stand fully on a stack of OSS, without the machinations (present or future) of massive companies to worry about, just the usefulness to the users.
