### ISSUE TITLE
Does not check rootUri in method `handleInitialize` in file workspaceFactory.ts

### ISSUE THREAD

**Issue by zbelial** [DetachHead/basedpyright#635]
I think it's a bug, and it causes basedpyright does not load pyrightconfig.json if a lsp client includes rootUri but not rootPath in initialize request. 

Originally I wanted to set `typeCheckingMode` to "off", but it didn't work if I set it in `initializationOptions`, then I created a pyrightconfig.json at the root of my project. But it didn't work too.  Then I tried to read basedpyright's code, and occasionally I found the issue described in the first paragraph, so I modified my lsp client to include both rootUri and rootPath, then it worked. 
So I think it's a real problem. 

I think pyright also has this problem. Because I was bothered by pyrightconfig.json not working in pyright months ago and switched to pylsp since not getting it work even asking for help from pyright.

Can you guys confirm it? thanks.

**Comment by DetachHead** [comment]
setting `typeCheckingMode` to `"off"` works for me. could you provide a bit more info please:

- what editor you're using
- does it happen in the CLI or language server or both?
- the whole contents of `pyrightconfig.json` and/or your language server config
- what version of basedpyright you're using

thanks

**Comment by zbelial** [comment]
Hi @DetachHead , thanks for your quick response. 

> setting `typeCheckingMode` to `"off"` works for me.

I guess, as I said above, your lsp client includes `rootPath` or `workspaceFolders` (which I forgot to mention above) in initialize params, does it? 

My lsp client only sent `rootUri` ( no `rootPath` and no `workspaceFolers` ) in initialize params , but after me adding `rootPath`, it works now.  

So I guess maybe it's because `handleInitialize` does not check `rootUri`, but it's just my guess, so I created this issue to get some confirmation, and hoped it may give you some hint if it's really a problem. 


> * what editor you're using

I'm using Emacs + lspce ( a lsp client I wrote )

> * does it happen in the CLI or language server or both?

I just tested the lauguage server before creating this issue. 

When you said CLI, did you mean `basedpyright` ?   I just run it at the project's root, it seemed work as expected (Only the disgnostics I expected showed). 

> * the whole contents of `pyrightconfig.json` and/or your language server config

It's very simple. Just to test whether it worked or not. 
```json
{
  "typeCheckingMode":"off",
  "reportMissingImports": "error",
  "reportMissingTypeStubs": false,
  "reportUndefinedVariable": "error",
  "reportUnusedVariable": "warning",
  "reportUnknownParameterType": false,
  "reportUnknownArgumentType": false,
  "reportUnknownLambdaType": false,
  "reportUnknownVariableType": false,
  "reportUnknownMemberType": false,
  "reportMissingParameterType": false,
  "reportUnusedCallResult": false,
  "pythonVersion": "3.11",
  "pythonPlatform": "Linux"
}

```

> * what version of basedpyright you're using
basedpyright 1.17.0
based on pyright 1.1.377

**Comment by zbelial** [comment]
But I think I shouldn't assert it's a problem in `handleInitialize` eagerly, sorry.  A little excited when pyrighconfig.json finally worked for me. :)

**Comment by DetachHead** [comment]
are you using the latest version (1.17.1)? if so can you see if it works in 1.17.0? it may be the same issue as #638

**Comment by zbelial** [comment]
> are you using the latest version (1.17.1)? if so can you see if it works in 1.17.0?  it may be the same issue as #638

I used 1.17.0 when I created this issue.  I just upgraded it to 1.17.1 and test it again with my lsp client (reverted to the version that had problems), it works now.  Seems  some commit after 1.17.0 fixes the problem. 

Sorry for the noise and thanks for your help. 

May I close this issue now?

**Comment by DetachHead** [comment]
awesome, must've been a different upstream issue that got fixed in the latest version
