### ISSUE TITLE
language server crashes when no workspace is open

### ISSUE THREAD

**Issue by DetachHead** [DetachHead/basedpyright#638]
> > you can download the `.vsix` from the [CI artifacts](https://github.com/DetachHead/basedpyright/actions/runs/10651928391/artifacts/1879004875), thanks
> 
> Ok, my bad 😅 Otherwise... bad news:
> 
> ![image](https://github.com/user-attachments/assets/89a731c8-182f-4d48-b424-729e11baa2df)
> 
> <details>
> <summary>LOG</summary>
> 
> Installed offline because if I installing online, I don't know why but it updating automatically.
> 
> > [Info  - 14:03:26] basedpyright language server 1.1.378 starting
> [Info  - 14:03:26] Server root directory: file:///e%3A/vscodium-portable/data/extensions/detachhead.basedpyright-1.1.378/dist
> [Info  - 14:03:26] Starting service instance "<default>"
> Received pythonPath from Python extension: C:\Users\MyPC\.pyenv\pyenv-win\versions\3.11.9\python.exe
> Received pythonPath from Python extension: C:\Users\MyPC\.pyenv\pyenv-win\versions\3.11.9\python.exe
> No pyproject.toml file found.
> [Info  - 14:03:26] Setting pythonPath for service "<default>": "c:\Users\MyPC\.pyenv\pyenv-win\versions\3.11.9\python.exe"
> [Info  - 14:03:26] No include entries specified; assuming \<default workspace root>
> [Info  - 14:03:26] Auto-excluding **/node_modules
> [Info  - 14:03:26] Auto-excluding **/__pycache__
> [Info  - 14:03:26] Auto-excluding **/.*
> [Info  - 14:03:26] Assuming Python version 3.11.9.final.0
> [Info  - 14:03:26] Search paths for file:///%3Cdefault%20workspace%20root%3E
> [Info  - 14:03:26]   e:\vscodium-portable\data\extensions\detachhead.basedpyright-1.1.378\dist\typeshed-fallback\stdlib
> [Info  - 14:03:26]   \<default workspace root>
> [Info  - 14:03:26]   \<default workspace root>\typings
> [Info  - 14:03:26]   e:\vscodium-portable\data\extensions\detachhead.basedpyright-1.1.378\dist\typeshed-fallback\stubs\...
> [Info  - 14:03:26]   c:\Users\MyPC\.pyenv\pyenv-win\versions\3.11.9\DLLs
> [Info  - 14:03:26]   c:\Users\MyPC\.pyenv\pyenv-win\versions\3.11.9\Lib
> [Info  - 14:03:26]   c:\Users\MyPC\.pyenv\pyenv-win\versions\3.11.9
> [Info  - 14:03:26]   c:\Users\MyPC\.pyenv\pyenv-win\versions\3.11.9\Lib\site-packages
> [Info  - 14:03:26] Adding fs watcher for library directories:
>  file:///c%3A/Users/MyPC/.pyenv/pyenv-win/versions/3.11.9/DLLs
> file:///c%3A/Users/MyPC/.pyenv/pyenv-win/versions/3.11.9/Lib
> file:///c%3A/Users/MyPC/.pyenv/pyenv-win/versions/3.11.9
> file:///c%3A/Users/MyPC/.pyenv/pyenv-win/versions/3.11.9/Lib/site-packages
> [Info  - 14:03:26] Adding fs watcher for directories:
>  file:///%3Cdefault%20workspace%20root%3E
> Searching for source files
> [Error - 14:03:26] File or directory "\<default workspace root>" does not exist.
> [Info  - 14:03:26] No source files found.
> [Info  - 14:03:26] Background analysis(1) root directory: file:///e%3A/vscodium-portable/data/extensions/detachhead.basedpyright-1.1.378/dist
> [Info  - 14:03:26] Background analysis(1) started
> No pyproject.toml file found.
> [Info  - 14:03:26] Setting pythonPath for service "<default>": "c:\Users\MyPC\.pyenv\pyenv-win\versions\3.11.9\python.exe"
> [Info  - 14:03:26] No include entries specified; assuming \<default workspace root>
> [Info  - 14:03:26] Auto-excluding **/node_modules
> [Info  - 14:03:26] Auto-excluding **/__pycache__
> [Info  - 14:03:26] Auto-excluding **/.*
> [Info  - 14:03:26] Assuming Python version 3.11.9.final.0
> [Info  - 14:03:26] Search paths for file:///%3Cdefault%20workspace%20root%3E
> [Info  - 14:03:26]   e:\vscodium-portable\data\extensions\detachhead.basedpyright-1.1.378\dist\typeshed-fallback\stdlib
> [Info  - 14:03:26]   \<default workspace root>
> [Info  - 14:03:26]   \<default workspace root>\typings
> [Info  - 14:03:26]   e:\vscodium-portable\data\extensions\detachhead.basedpyright-1.1.378\dist\typeshed-fallback\stubs\...
> [Info  - 14:03:26]   c:\Users\MyPC\.pyenv\pyenv-win\versions\3.11.9\DLLs
> [Info  - 14:03:26]   c:\Users\MyPC\.pyenv\pyenv-win\versions\3.11.9\Lib
> [Info  - 14:03:26]   c:\Users\MyPC\.pyenv\pyenv-win\versions\3.11.9
> [Info  - 14:03:26]   c:\Users\MyPC\.pyenv\pyenv-win\versions\3.11.9\Lib\site-packages
> [Info  - 14:03:26] Adding fs watcher for library directories:
>  file:///c%3A/Users/MyPC/.pyenv/pyenv-win/versions/3.11.9/DLLs
> file:///c%3A/Users/MyPC/.pyenv/pyenv-win/versions/3.11.9/Lib
> file:///c%3A/Users/MyPC/.pyenv/pyenv-win/versions/3.11.9
> file:///c%3A/Users/MyPC/.pyenv/pyenv-win/versions/3.11.9/Lib/site-packages
> [Info  - 14:03:26] Adding fs watcher for directories:
>  file:///%3Cdefault%20workspace%20root%3E
> Searching for source files
> [Error - 14:03:26] File or directory "\<default workspace root>" does not exist.
> [Info  - 14:03:26] No source files found.
> [BG(1)] analyzing: untitled:Untitled-1 ...
> [BG(1)]   parsing: untitled:Untitled-1 (112ms)
> [BG(1)]   parsing: file:///e%3A/vscodium-portable/data/extensions/detachhead.basedpyright-1.1.378/dist/typeshed-fallback/stdlib/builtins.pyi [fs read 4ms] (112ms)
> [BG(1)]   binding: file:///e%3A/vscodium-portable/data/extensions/detachhead.basedpyright-1.1.378/dist/typeshed-fallback/stdlib/builtins.pyi (46ms)
> [BG(1)]   binding: untitled:Untitled-1 (0ms)
> [BG(1)]   checking: untitled:Untitled-1 ...
> [BG(1)]     parsing: file:///e%3A/vscodium-portable/data/extensions/detachhead.basedpyright-1.1.378/dist/typeshed-fallback/stdlib/typing.pyi [fs read 1ms] (29ms)
> [BG(1)]     binding: file:///e%3A/vscodium-portable/data/extensions/detachhead.basedpyright-1.1.378/dist/typeshed-fallback/stdlib/typing.pyi (9ms)
> [BG(1)]     parsing: file:///e%3A/vscodium-portable/data/extensions/detachhead.basedpyright-1.1.378/dist/typeshed-fallback/stdlib/types.pyi [fs read 1ms] (24ms)
> [BG(1)]     binding: file:///e%3A/vscodium-portable/data/extensions/detachhead.basedpyright-1.1.378/dist/typeshed-fallback/stdlib/types.pyi (10ms)
> [BG(1)]     parsing: file:///e%3A/vscodium-portable/data/extensions/detachhead.basedpyright-1.1.378/dist/typeshed-fallback/stdlib/_typeshed/__init__.pyi [fs read 1ms] (6ms)
> [BG(1)]     binding: file:///e%3A/vscodium-portable/data/extensions/detachhead.basedpyright-1.1.378/dist/typeshed-fallback/stdlib/_typeshed/__init__.pyi (9ms)
> [BG(1)]     parsing: file:///e%3A/vscodium-portable/data/extensions/detachhead.basedpyright-1.1.378/dist/typeshed-fallback/stdlib/abc.pyi [fs read 1ms] (2ms)
> [BG(1)]     binding: file:///e%3A/vscodium-portable/data/extensions/detachhead.basedpyright-1.1.378/dist/typeshed-fallback/stdlib/abc.pyi (1ms)
> [BG(1)]   checking: untitled:Untitled-1 (163ms)
> [BG(1)] analyzing: untitled:Untitled-1 (439ms)
> [Info  - 14:03:46] Starting service instance "<default>"
> WorkspaceFactory 0 remove <default>
> WorkspaceFactory 0 add <default>
> Received pythonPath from Python extension: C:\Users\MyPC\.pyenv\pyenv-win\versions\3.11.9\python.exe
> No pyproject.toml file found.
> [Info  - 14:03:46] Setting pythonPath for service "<default>": "c:\Users\MyPC\.pyenv\pyenv-win\versions\3.11.9\python.exe"
> [Info  - 14:03:46] No include entries specified; assuming \<default workspace root>
> [Info  - 14:03:46] Auto-excluding **/node_modules
> [Info  - 14:03:46] Auto-excluding **/__pycache__
> [Info  - 14:03:46] Auto-excluding **/.*
> [Info  - 14:03:46] Assuming Python version 3.11.9.final.0
> [Info  - 14:03:46] Search paths for file:///%3Cdefault%20workspace%20root%3E
> [Info  - 14:03:46]   e:\vscodium-portable\data\extensions\detachhead.basedpyright-1.1.378\dist\typeshed-fallback\stdlib
> [Info  - 14:03:46]   \<default workspace root>
> [Info  - 14:03:46]   \<default workspace root>\typings
> [Info  - 14:03:46]   e:\vscodium-portable\data\extensions\detachhead.basedpyright-1.1.378\dist\typeshed-fallback\stubs\...
> [Info  - 14:03:46]   c:\Users\MyPC\.pyenv\pyenv-win\versions\3.11.9\DLLs
> [Info  - 14:03:46]   c:\Users\MyPC\.pyenv\pyenv-win\versions\3.11.9\Lib
> [Info  - 14:03:46]   c:\Users\MyPC\.pyenv\pyenv-win\versions\3.11.9
> [Info  - 14:03:46]   c:\Users\MyPC\.pyenv\pyenv-win\versions\3.11.9\Lib\site-packages
> [Info  - 14:03:46] Adding fs watcher for library directories:
>  file:///c%3A/Users/MyPC/.pyenv/pyenv-win/versions/3.11.9/DLLs
> file:///c%3A/Users/MyPC/.pyenv/pyenv-win/versions/3.11.9/Lib
> file:///c%3A/Users/MyPC/.pyenv/pyenv-win/versions/3.11.9
> file:///c%3A/Users/MyPC/.pyenv/pyenv-win/versions/3.11.9/Lib/site-packages
> [Info  - 14:03:46] Adding fs watcher for directories:
>  file:///%3Cdefault%20workspace%20root%3E
> Searching for source files
> [Error - 14:03:46] File or directory "\<default workspace root>" does not exist.
> [Info  - 14:03:46] No source files found.
> [Info  - 14:03:46] Starting service instance "<default>"
> WorkspaceFactory 0 remove <default>
> WorkspaceFactory 0 add <default>
> Received pythonPath from Python extension: C:\Users\MyPC\.pyenv\pyenv-win\versions\3.11.9\python.exe
> No pyproject.toml file found.
> [Info  - 14:03:46] Setting pythonPath for service "<default>": "c:\Users\MyPC\.pyenv\pyenv-win\versions\3.11.9\python.exe"
> [Info  - 14:03:46] No include entries specified; assuming \<default workspace root>
> [Info  - 14:03:46] Auto-excluding **/node_modules
> [Info  - 14:03:46] Auto-excluding **/__pycache__
> [Info  - 14:03:46] Auto-excluding **/.*
> [Info  - 14:03:46] Assuming Python version 3.11.9.final.0
> [Info  - 14:03:46] Search paths for file:///%3Cdefault%20workspace%20root%3E
> [Info  - 14:03:46]   e:\vscodium-portable\data\extensions\detachhead.basedpyright-1.1.378\dist\typeshed-fallback\stdlib
> [Info  - 14:03:46]   \<default workspace root>
> [Info  - 14:03:46]   \<default workspace root>\typings
> [Info  - 14:03:46]   e:\vscodium-portable\data\extensions\detachhead.basedpyright-1.1.378\dist\typeshed-fallback\stubs\...
> [Info  - 14:03:46]   c:\Users\MyPC\.pyenv\pyenv-win\versions\3.11.9\DLLs
> [Info  - 14:03:46]   c:\Users\MyPC\.pyenv\pyenv-win\versions\3.11.9\Lib
> [Info  - 14:03:46]   c:\Users\MyPC\.pyenv\pyenv-win\versions\3.11.9
> [Info  - 14:03:46]   c:\Users\MyPC\.pyenv\pyenv-win\versions\3.11.9\Lib\site-packages
> [Info  - 14:03:46] Adding fs watcher for library directories:
>  file:///c%3A/Users/MyPC/.pyenv/pyenv-win/versions/3.11.9/DLLs
> file:///c%3A/Users/MyPC/.pyenv/pyenv-win/versions/3.11.9/Lib
> file:///c%3A/Users/MyPC/.pyenv/pyenv-win/versions/3.11.9
> file:///c%3A/Users/MyPC/.pyenv/pyenv-win/versions/3.11.9/Lib/site-packages
> [Info  - 14:03:46] Adding fs watcher for directories:
>  file:///%3Cdefault%20workspace%20root%3E
> Searching for source files
> [Error - 14:03:46] File or directory "\<default workspace root>" does not exist.
> [Info  - 14:03:46] No source files found.
> [Error - 14:03:46] Request textDocument/inlayHint failed.
>   Message: Request textDocument/inlayHint failed with message: Cannot read properties of undefined (reading 'tokenizerOutput')
>   Code: -32603 
> [Info  - 14:03:46] Background analysis(2) root directory: file:///e%3A/vscodium-portable/data/extensions/detachhead.basedpyright-1.1.378/dist
> [Info  - 14:03:46] Background analysis(2) started
> [Info  - 14:03:46] Starting service instance "<default>"
> WorkspaceFactory 0 remove <default>
> WorkspaceFactory 0 add <default>
> Received pythonPath from Python extension: C:\Users\MyPC\.pyenv\pyenv-win\versions\3.11.9\python.exe
> No pyproject.toml file found.
> [Info  - 14:03:46] Setting pythonPath for service "<default>": "c:\Users\MyPC\.pyenv\pyenv-win\versions\3.11.9\python.exe"
> [Info  - 14:03:46] No include entries specified; assuming \<default workspace root>
> [Info  - 14:03:46] Auto-excluding **/node_modules
> [Info  - 14:03:46] Auto-excluding **/__pycache__
> [Info  - 14:03:46] Auto-excluding **/.*
> [Info  - 14:03:46] Assuming Python version 3.11.9.final.0
> [Info  - 14:03:46] Search paths for file:///%3Cdefault%20workspace%20root%3E
> [Info  - 14:03:46]   e:\vscodium-portable\data\extensions\detachhead.basedpyright-1.1.378\dist\typeshed-fallback\stdlib
> [Info  - 14:03:46]   \<default workspace root>
> [Info  - 14:03:46]   \<default workspace root>\typings
> [Info  - 14:03:46]   e:\vscodium-portable\data\extensions\detachhead.basedpyright-1.1.378\dist\typeshed-fallback\stubs\...
> [Info  - 14:03:46]   c:\Users\MyPC\.pyenv\pyenv-win\versions\3.11.9\DLLs
> [Info  - 14:03:46]   c:\Users\MyPC\.pyenv\pyenv-win\versions\3.11.9\Lib
> [Info  - 14:03:46]   c:\Users\MyPC\.pyenv\pyenv-win\versions\3.11.9
> [Info  - 14:03:46]   c:\Users\MyPC\.pyenv\pyenv-win\versions\3.11.9\Lib\site-packages
> [Info  - 14:03:46] Adding fs watcher for library directories:
>  file:///c%3A/Users/MyPC/.pyenv/pyenv-win/versions/3.11.9/DLLs
> file:///c%3A/Users/MyPC/.pyenv/pyenv-win/versions/3.11.9/Lib
> file:///c%3A/Users/MyPC/.pyenv/pyenv-win/versions/3.11.9
> file:///c%3A/Users/MyPC/.pyenv/pyenv-win/versions/3.11.9/Lib/site-packages
> [Info  - 14:03:46] Adding fs watcher for directories:
>  file:///%3Cdefault%20workspace%20root%3E
> Searching for source files
> [Error - 14:03:46] File or directory "\<default workspace root>" does not exist.
> [Info  - 14:03:46] No source files found.
> [Info  - 14:03:46] Starting service instance "<default>"
> WorkspaceFactory 0 remove <default>
> WorkspaceFactory 0 add <default>
> Received pythonPath from Python extension: C:\Users\MyPC\.pyenv\pyenv-win\versions\3.11.9\python.exe
> [Info  - 14:03:46] Starting service instance "<default>"
> WorkspaceFactory 0 remove <default>
> WorkspaceFactory 0 add <default>
> Received pythonPath from Python extension: C:\Users\MyPC\.pyenv\pyenv-win\versions\3.11.9\python.exe
> [Info  - 14:03:46] Background analysis(3) root directory: file:///e%3A/vscodium-portable/data/extensions/detachhead.basedpyright-1.1.378/dist
> [Info  - 14:03:46] Background analysis(3) started
> No pyproject.toml file found.
> [Info  - 14:03:46] Setting pythonPath for service "<default>": "c:\Users\MyPC\.pyenv\pyenv-win\versions\3.11.9\python.exe"
> [Info  - 14:03:46] No include entries specified; assuming \<default workspace root>
> [Info  - 14:03:46] Auto-excluding **/node_modules
> [Info  - 14:03:46] Auto-excluding **/__pycache__
> [Info  - 14:03:46] Auto-excluding **/.*
> [Info  - 14:03:46] Assuming Python version 3.11.9.final.0
> [Info  - 14:03:47] Search paths for file:///%3Cdefault%20workspace%20root%3E
> [Info  - 14:03:47]   e:\vscodium-portable\data\extensions\detachhead.basedpyright-1.1.378\dist\typeshed-fallback\stdlib
> [Info  - 14:03:47]   \<default workspace root>
> [Info  - 14:03:47]   \<default workspace root>\typings
> [Info  - 14:03:47]   e:\vscodium-portable\data\extensions\detachhead.basedpyright-1.1.378\dist\typeshed-fallback\stubs\...
> [Info  - 14:03:47]   c:\Users\MyPC\.pyenv\pyenv-win\versions\3.11.9\DLLs
> [Info  - 14:03:47]   c:\Users\MyPC\.pyenv\pyenv-win\versions\3.11.9\Lib
> [Info  - 14:03:47]   c:\Users\MyPC\.pyenv\pyenv-win\versions\3.11.9
> [Info  - 14:03:47]   c:\Users\MyPC\.pyenv\pyenv-win\versions\3.11.9\Lib\site-packages
> [Info  - 14:03:47] Adding fs watcher for library directories:
>  file:///c%3A/Users/MyPC/.pyenv/pyenv-win/versions/3.11.9/DLLs
> file:///c%3A/Users/MyPC/.pyenv/pyenv-win/versions/3.11.9/Lib
> file:///c%3A/Users/MyPC/.pyenv/pyenv-win/versions/3.11.9
> file:///c%3A/Users/MyPC/.pyenv/pyenv-win/versions/3.11.9/Lib/site-packages
> [Info  - 14:03:47] Adding fs watcher for directories:
>  file:///%3Cdefault%20workspace%20root%3E
> Searching for source files
> [Error - 14:03:47] File or directory "\<default workspace root>" does not exist.
> [Info  - 14:03:47] No source files found.
> [Info  - 14:03:47] Background analysis(4) root directory: file:///e%3A/vscodium-portable/data/extensions/detachhead.basedpyright-1.1.378/dist
> [Info  - 14:03:47] Background analysis(4) started
> No pyproject.toml file found.
> [Info  - 14:03:47] Setting pythonPath for service "<default>": "c:\Users\MyPC\.pyenv\pyenv-win\versions\3.11.9\python.exe"
> [Info  - 14:03:47] No include entries specified; assuming \<default workspace root>
> [Info  - 14:03:47] Auto-excluding **/node_modules
> [Info  - 14:03:47] Auto-excluding **/__pycache__
> [Info  - 14:03:47] Auto-excluding **/.*
> [Info  - 14:03:47] Assuming Python version 3.11.9.final.0
> [Info  - 14:03:47] Search paths for file:///%3Cdefault%20workspace%20root%3E
> [Info  - 14:03:47]   e:\vscodium-portable\data\extensions\detachhead.basedpyright-1.1.378\dist\typeshed-fallback\stdlib
> [Info  - 14:03:47]   \<default workspace root>
> [Info  - 14:03:47]   \<default workspace root>\typings
> [Info  - 14:03:47]   e:\vscodium-portable\data\extensions\detachhead.basedpyright-1.1.378\dist\typeshed-fallback\stubs\...
> [Info  - 14:03:47]   c:\Users\MyPC\.pyenv\pyenv-win\versions\3.11.9\DLLs
> [Info  - 14:03:47]   c:\Users\MyPC\.pyenv\pyenv-win\versions\3.11.9\Lib
> [Info  - 14:03:47]   c:\Users\MyPC\.pyenv\pyenv-win\versions\3.11.9
> [Info  - 14:03:47]   c:\Users\MyPC\.pyenv\pyenv-win\versions\3.11.9\Lib\site-packages
> [Info  - 14:03:47] Adding fs watcher for library directories:
>  file:///c%3A/Users/MyPC/.pyenv/pyenv-win/versions/3.11.9/DLLs
> file:///c%3A/Users/MyPC/.pyenv/pyenv-win/versions/3.11.9/Lib
> file:///c%3A/Users/MyPC/.pyenv/pyenv-win/versions/3.11.9
> file:///c%3A/Users/MyPC/.pyenv/pyenv-win/versions/3.11.9/Lib/site-packages
> [Info  - 14:03:47] Adding fs watcher for directories:
>  file:///%3Cdefault%20workspace%20root%3E
> Searching for source files
> [Error - 14:03:47] File or directory "\<default workspace root>" does not exist.
> [Info  - 14:03:47] No source files found.
> [Info  - 14:03:47] Background analysis(6) root directory: file:///e%3A/vscodium-portable/data/extensions/detachhead.basedpyright-1.1.378/dist
> [Info  - 14:03:47] Background analysis(6) started
> [Info  - 14:03:47] Background analysis(5) root directory: file:///e%3A/vscodium-portable/data/extensions/detachhead.basedpyright-1.1.378/dist
> [Info  - 14:03:47] Background analysis(5) started
> </details>
> 

_Originally posted by @felix9743 in https://github.com/DetachHead/basedpyright/issues/592#issuecomment-2323315184_
            

this seems to be an upstream issue where all lsp features don't work unless a workspace is open (ie. when it can't determine the project root), though you won't get the same error about inlay hints obviously because pyright doesn't have inlay hints.

**Comment by felix9743** [comment]
> One more thing: it appears that version 1.1.378 attempts to access a default workspace when no folders or workspaces are open in the IDE. However, since it is trying to access a non-existent location, it cannot work which would cause the malfunction.
> 
> > [Info - 14:03:47] Adding fs watcher for directories:
> > file:///%3Cdefault%20workspace%20root%3E
> > Searching for source files
> > [Error - 14:03:47] File or directory "" does not exist.
> > [Info - 14:03:47] No source files found.
> 
> He therefore tries to access this location: `file:///<default workspace root>`
> 
> I don't know if it's the same problem for version 1.15.2 and above but it seems likely to me.

As explained in #592, this seems to come from the fact that the default workspace location defined in the extension does not exist which therefore generates an error (normal or fatal, I don't know). You can find the lines which define this information [here](https://github.com/DetachHead/basedpyright/blob/dc566963cf42417111ae4c15b77c736a17220d41/packages/pyright-internal/src/common/uri/uri.ts#L239-L240).

**Comment by akmalsoliev** [comment]
Hello, facing similar issues 
`NVIM v0.10.1`
`uv 0.4.2`
os: `MacOS 14.6.1`

**Comment by skimask9** [comment]
Same here
` basedpyright v1.17.2`
`NVIM v0.10.1`




`
[ERROR][2024-09-01 19:00:11] ...lsp/handlers.lua:623	'File or directory "/<default workspace root>" does not exist.'
[ERROR][2024-09-01 19:00:12] ...lsp/handlers.lua:623	'File or directory "/<default workspace root>" does not exist.'
[ERROR][2024-09-01 19:00:13] ...lsp/handlers.lua:623	'File or directory "/<default workspace root>" does not exist.'
[ERROR][2024-09-01 19:00:14] ...lsp/handlers.lua:623	'File or directory "/<default workspace root>" does not exist.'
[ERROR][2024-09-01 19:00:16] ...lsp/handlers.lua:623	'File or directory "/<default workspace root>" does not exist.'
[ERROR][2024-09-01 19:00:17] ...lsp/handlers.lua:623	'File or directory "/<default workspace root>" does not exist.'
[ERROR][2024-09-01 19:00:18] ...lsp/handlers.lua:623	'File or directory "/<default workspace root>" does not exist.'
[ERROR][2024-09-01 19:00:19] ...lsp/handlers.lua:623	'File or directory "/<default workspace root>" does not exist.'
[ERROR][2024-09-01 19:00:19] ...lsp/handlers.lua:623	'File or directory "/<default workspace root>" does not exist.'
`

**Comment by DetachHead** [comment]
this was caused by a change the pylance team ported to pyright that seems to have only contained part of the code necessary for it to work. this caused the language server to instantly close on startup. i have no idea what it was for so i just removed it which seems to have fixed the issue (3c7cfd98850c42f494fb2d27899cc51322e5b984)

the fix will be included in the next release.

**Comment by maryjeck** [comment]
> this was caused by a change the pylance team ported to pyright that seems to have only contained part of the code necessary for it to work. this caused the language server to instantly close on startup. i have no idea what it was for so i just removed it which seems to have fixed the issue ([3c7cfd9](https://github.com/DetachHead/basedpyright/commit/3c7cfd98850c42f494fb2d27899cc51322e5b984))这是由 Pylance 团队移植到 Pyright 的一个更改引起的，该更改似乎只包含其工作所需的部分代码。这会导致 Language Server 在启动时立即关闭。我不知道它是做什么的，所以我只是删除了它，这似乎已经解决了问题 （）[ 3c7cfd9 ](https://github.com/DetachHead/basedpyright/commit/3c7cfd98850c42f494fb2d27899cc51322e5b984)
> 
> the fix will be included in the next release.此修复程序将包含在下一个版本中。

Is there a temporary way to use it?

**Comment by DetachHead** [comment]
just released 1.17.3 with the fix

**Comment by simondoesstuff** [comment]
I am still having this issue. It will take time to create a MRE, but

basedpyright 1.28.4
(based on pyright 1.1.398)
NVIM v0.11.0
using nixvim:  commit d4dada282aeac94b5d53dd70e276a2f5f534f783
(ARM) OSX: 15.3.2

The issue is related to the `pyproject.toml` config option:
```yml
[tool.basedpyright]
executionEnvironments = [
  { root = "src" },
]
```

**Comment by DetachHead** [comment]
sounds like a different issue. can you try on the latest release (1.29.1)? if it still doesn't work i suggest opening a separate issue
