### ISSUE TITLE
No long working in single file mode after upgrading to 1.17.1 version

### ISSUE THREAD

**Issue by madjxatw** [DetachHead/basedpyright#640]
Using Neovim LSP + basepyright to edit a single python script (not a python project, hence no root dir), LSP-based intelligence no long works after upgrading basepyright to 1.17.1. Everything was working smoothly before, no configuration has been changed though. However, there is no problem in a python project directory that contains e.g. `pyproject.toml`, `pyrightconfig.json` or even `.git/`.

**Comment by DetachHead** [comment]
merging with #638
