### ISSUE TITLE
Paths to include or exclude don't work properly

### ISSUE THREAD

**Issue by willofferfit** [DetachHead/basedpyright#643]
`basedpyright.analysis.exclude` doesn't work for me in any version, which makes basedpyright unusable (e.g. it wants to analyze my `.venv` with 37k files). If I downgrade to v1.15.2 and use `basedpyright.analysis.include`, then it respects that at least, but starting at v1.16.0 it fails too.

Versions:
- vscodium 1.92.2
- basedpyright 1.16.0+
- Python 3.10.6
- macOS 14.5

Config:
```json
{
    "python.languageServer": "None",
    "basedpyright.analysis.diagnosticMode": "workspace",
    "basedpyright.analysis.include": ["redacted"],
    "basedpyright.analysis.exclude": [
        ".venv",
        ".git",
        "**/__pycache__",
    ],
    "basedpyright.analysis.typeCheckingMode": "strict",
    "basedpyright.analysis.logLevel": "Error",
    "basedpyright.analysis.diagnosticSeverityOverrides": {
        "reportAny": "none",
        "reportPrivateUsage": "none",
        "reportUnknownMemberType": "none",
        "reportImplicitStringConcatenation": "none",
    },
    "basedpyright.importStrategy": "fromEnvironment",
}
```

**Comment by DetachHead** [comment]
do you have a `pyrightconfig.json`   or `pyproject.toml` with a `tool.pyright`/`tool.basedpyright` section in it? a recent upstream change made it so that language server/vscode settings are always ignored in that case

**Comment by willofferfit** [comment]
Yes, I have `pyproject.toml` with a `tool.pyright` section. If I delete it, then v1.17.1 works as expected. Thanks!

**Comment by DetachHead** [comment]
no problem. ideally there should be a warning that lets you know when this happens (#513)
