### ISSUE TITLE
coc-basedpyright issue in vim using coc

### ISSUE THREAD

**Issue by tahseenjamal** [DetachHead/basedpyright#654]
I have install vim, latest version on Mac sonoma
Using Vundle, I installed coc and then I installed using coc the extension coc-basedpyright
Now when I open certain files, it throws error on the imports as Stub file not found
Also throws error on unable to read stubPath

I tried using CocConfig and in that I tried every possible setting and nothing is   working

**Comment by DetachHead** [comment]
can you post the exact error message

**Comment by tahseenjamal** [comment]
Steps to repeat
1. Install VIM, install coc plugin and then run inside it `:CocInstall coc-basedpyright`
2. Mini Conda Installed
3. Created new environment with python 3.11 and masonite 4 framework
4. Switched to this new environment
5. Created a new `project project start blog`
6. Then go into the blog folder
7. Open vi and then open any controller file like default is WelcomeController.py

[coc.nvim] Request workspace/configuration failed with message: Cannot read properties of undefined (reading 'stubPath')

**Comment by DetachHead** [comment]
do you have a `pyproject.toml` or `pyrightconfig.json` file? if so can you share those as well please

**Comment by tahseenjamal** [comment]
There is no pyrightconfig.json in the project folder. But yes there is pyproject.toml and below is the content of the same

`❯ cat pyproject.toml`


```
[tool.black]
line-length = 99
target-version = ['py37']
include = '\.pyi?$'
exclude = '(\.git|\.venv|\.idea|templates|resources|storage|databases\/migrations|node_modules)'

[tool.pytest.ini_options]
minversion = "6.0"
testpaths = [
  "tests",
]
```

**Comment by tahseenjamal** [comment]
This case is only for VIM, I don't see issue in basedpyright when using with NeoVim

**Comment by DetachHead** [comment]
yeah i just use the same label for both vim and neovim because i don't know much about them but i assume they're similar enough that it makes sense to have them both under one label. to me the label just means "the editor that's a pain in the ass to set up" lol

**Comment by tahseenjamal** [comment]
Just to tell you that there is `:CocConfig` to configure basedpyright parameters. But unfortunately, even when I am disabling reportMissingTypeStubs, somehow basedpyright is not able to check it.

```
{
    "basedpyright.analysis.diagnosticSeverityOverrides": {
        "reportMissingTypeStubs": false
    }
}
```

**Comment by DetachHead** [comment]
thanks for the info, i'll try to investigate. in the mean time it may also be worth raising this at https://github.com/fannheyward/coc-basedpyright in case the issue is on their end

**Comment by tahseenjamal** [comment]
Thanks, looks like coc-basedpyright expects configuration in the pyproject.toml, after I appended below, the errors on imports went away. Means coc-basedpyright is reading configurations from pyproject.toml

[tool.basedpyright]
reportMissingTypeStubs = false

You can close this ticket, it I have to configure the pyproject.toml
