### ISSUE TITLE
support python 3.6

### ISSUE THREAD

**Issue by DetachHead** [DetachHead/basedpyright#658]
3.6 has been EOL for a few years, but since pyright supports it we probably should too

**Comment by DetachHead** [comment]
python 3.6 is supported if you install basedpyright from npm (#953)

**Comment by KotlinIsland** [comment]
is this really a good idea considering that typeshed only supports >=3.8 and all stub references to <3.8 are removed?

**Comment by DetachHead** [comment]
idk, this is just whatever 3.6 support that's still in pyright itself, because someone who was using pyright on 3.6 asked for us to support it.

**Comment by KotlinIsland** [comment]
there should probably be a warning, I think it would be a nightmare ux if all the types were wrong in a type checker
