### ISSUE TITLE
`isinstance` checks on classes with generics should narrow to the generic's bound if it's covariant, and `Never` if it's contravariant

### ISSUE THREAD

**Issue by DetachHead** [DetachHead/basedpyright#674]
Code sample in [basedpyright playground](https://basedpyright.com/?typeCheckingMode=all&reportImplicitOverride=true&code=MYGwhgzhAEBiD28DaAVAXNAlgOwC7QB9oJcAnAXTQFgAoae6AEwFMAzaVxACgmZFYA00eLgAWzUhngAjAFbNguAJTU6DdZnaYIOEmGzBmXEeNJCE8FbXU2GpZgDdmYEAH1cATwAORkxKXQAMRwiEgAqtgA1tjwAO7Y5EIQovAAriCM0NLMIcg4%2BEQkFEA)

```python
class Foo[T: int | str]:
    def foo(self, other: object):
        if isinstance(other, Foo):
            reveal_type(other) # Foo[Unknown], should be Foo[int | str]
```
if the generic is covariant it should narrow to `Foo[int | str]` (or whatever the generic's bound is), and if it's contravariant it should narrow to `Foo[Never]` i think

**Comment by UltimateLobster** [comment]
It doesn't seem like there's enough information here to come to this conclusion because the `other` argument has no generic connection to `self` (The `T` is never used to annotate anything about `other`).

So the only conclusion I can see here is that `other` should be of type `Foo[BoundOfT]`

**Comment by DetachHead** [comment]
yeah that's what i meant sorry, updated the example to be more clear
