### ISSUE TITLE
vscode links to docs go to main branch which might not have the doc in question

### ISSUE THREAD

**Issue by sparr** [DetachHead/basedpyright#713]
In VSCode(...ium) the tooltip for an underlined warning or error includes a link to the docs on github where the rule in question is explained. Those links go to the main branch of this repo, which makes them broken links if the main branch has changes to the docs structure.

For example, v1.18.0 of the extension produces links like https://github.com/detachhead/basedpyright/blob/main/docs/configuration.md#reportImplicitOverride but docs/configuration.md doesn't exist in the main branch any more, it was replaced by [docs/configuration/config-files.md](https://github.com/detachhead/basedpyright/blob/main/docs/configuration/config-files.md#reportImplicitOverride).

The links should go to the commit or tag that the extension was built from (or possibly a branch or tag that tracks non-breaking changes?), so they will remain functional and accurate in the future.

Having written all that, it looks like the main branch is moving to hosting the docs on basedpyright.com which will mean this concern only applies to older versions. Maybe it's worth fixing in those versions. Maybe configuration.md could just be a symlink to the new file location?

**Comment by DetachHead** [comment]
sorry about that, i just redid the docs site so all those links will be broken until the next release

**Comment by sparr** [comment]
Would you consider patches to older versions that are still in use, so they use links to the new docs site?
