### ISSUE TITLE
move diagnostic rule docs back to where it was for backwards compatibility with old versions

### ISSUE THREAD

**Issue by KotlinIsland** [DetachHead/basedpyright#719]
Would you consider patches to older versions that are still in use, so they use links to the new docs site?

_Originally posted by @sparr in https://github.com/DetachHead/basedpyright/issues/713#issuecomment-2383498112_

**Comment by DetachHead** [comment]
probably gonna just move that section of the docs back to where it was, then import it in the new docs using [mkdocs snippets](https://facelessuser.github.io/pymdown-extensions/extensions/snippets/)
