### ISSUE TITLE
config option to fail on warnings + replace `"all"` `typeCheckingMode` with new `"recommended"` where less serious diagnostics are warnings instead of error

### ISSUE THREAD

**Issue by DetachHead** [DetachHead/basedpyright#728]
related: #315

it should probably default to the [most strict](https://docs.basedpyright.com/latest/benefits-over-pyright/better-defaults/). use case is that you want to differentiate between actual errors (likely to cause runtime crash) vs lint errors that won't necessarily crash but you still want to fail the CI

**Comment by KotlinIsland** [comment]
having every rule error by default makes visually parsing a non trivially large error list quite difficult, and (nit) makes it harder at first glance to understand what is happening in a line of code

**Comment by DetachHead** [comment]
`--warnings` already exists, but im going to add a new config file option called `failOnWarnings` to make it so that the new `"recommended"` `typeCheckingMode` still fails in the cli when any diagnostics are present
