### ISSUE TITLE
[Non-programming request] May the maintainer change his currently creepy avatar?

### ISSUE THREAD

**Issue by daanturo** [DetachHead/basedpyright#735]
(I assume their gender is man, please forgive me otherwise.)

I have this repo starred, so maybe because of that basedpyright's releases shows his [avatar](https://avatars.githubusercontent.com/u/57028336?v=4) when entering github.com/. 

Seeing the image sent shiver my spine and my heart nearly stopped for a moment.

I know this is a too luxury request, but honestly I'm genuinely scared by your avatar. It even makes me hesitate to visit this page.

**Comment by DetachHead** [comment]
lol i like my profile picture so i have no plans to change it, but i guess that won't be an issue when i get around to doing #370
