### ISSUE TITLE
false `reportShadowedImports` positive

### ISSUE THREAD

**Issue by karolyi** [DetachHead/basedpyright#760]
Hey,

With using python3.10, I have a venv with `--system-site-packages` installed. In that venv, I've installed `typing_extensions` on the local level (not `--user`), and the user venv (in `~/.local/lib/python3.10/site-packages/`) doesn't contain this package.

In that version of the venv, doing a `from typing_extensions import override` statement will give me a `reportShadowedImports` error, offering renaming the package itself to something else. If I uninstall the package, I get the 'package not found' error. The exact error is:
```
"/home/user/project/venv/lib/python3.10/site-packages/typing_extensions.py" is overriding the stdlib module "typing_extensions".
```

But `typing_extensions` was never a part of python stdlib.

Unfortunately I can't give you a pyright playground example for this, because I can't install packages there.

A hint might be another venv where I use the same package, without using `--system-site-packages`. I don't get this error there.

Also, I tried deinstalling basedpyright and installing pyright to see if the bug originates there, but pyright doesn't have this issue.

**Comment by karolyi** [comment]
Please stand by with further investigating until I test once more with pyright, with `reportShadowedImports` enabled. Gonna happen tomorrow, my desktop is switched off for today.

**Comment by DetachHead** [comment]
no worries, if your issue gets closed without a solution let us know and we can re-open this issue
