### ISSUE TITLE
[Feature Request] Add code action for auto import

### ISSUE THREAD

**Issue by johnpyp** [DetachHead/basedpyright#78]
This feature was highly requested on Pyright itself, but they denied it due to it being part of proprietary Pylance, and not wanting to build on actual LSP features in Pyright. It would be nice to have an alternative that does enable those things!

https://github.com/microsoft/pyright/issues/4263

**Comment by KotlinIsland** [comment]
Has this been requested on Pylance instead of Pyright?

**Comment by DetachHead** [comment]
i don't get what's up with import suggestions in pyright. i noticed that without pylance the suggested imports still appeared for me but only occasionally, so i figured it was a bug with pyright. but if it's something they deliberately make exclusive to pylance that's super annoying and something i would consider high priority for basedpyright.

**Comment by DetachHead** [comment]
as a workaround, the next release will support enabling both the basedpyright and pylance extensions at the same time, which will allow you to use pylance's LSP alongside basedpyright's typechecking (#35)

**Comment by johnpyp** [comment]
I don’t actually want to use Pylance, as I’m using neovim, not vscode :) that’s my main issue with Pyright as is. And the Pyright team won’t add these features that encroach on Pylance’s “value”

**Comment by johnpyp** [comment]
Specifically, you get auto completion import suggestions with Pyright, but you don’t get code actions or other kind of import related functionality you’d expect (code action is the main one I want)

**Comment by KotlinIsland** [comment]
Does https://github.com/fannheyward/coc-pyright support this functionality?

**Comment by DetachHead** [comment]
> Specifically, you get auto completion import suggestions with Pyright, but you don’t get code actions or other kind of import related functionality you’d expect (code action is the main one I want)

by "auto completion import suggestions", do you mean the suggested imports that appear as you're typing?

![image](https://github.com/DetachHead/basedpyright/assets/57028336/0c3c10ad-39bc-4660-b373-4bb213fd23f7)

and by "code actions" do you mean the "quick fix" import suggestions that appear on errors, which don't seem to be present in pyright?

![image](https://github.com/DetachHead/basedpyright/assets/57028336/5036a3ae-8ac3-4501-bfb0-c76f99e2acbb)

sorry i've never used neovim and i have barely any experience with language servers so i just want to make sure we're on the same page here.

**Comment by johnpyp** [comment]
Yep exactly

**Comment by johnpyp** [comment]
> Does [coc-pyright](https://github.com/fannheyward/coc-pyright) support this functionality?

Yes it does, but you can’t use it as an independent language server

**Comment by DetachHead** [comment]
this will be included in basedpyright 1.3.0, which i aim to release within the next day or so

**Comment by johnpyp** [comment]
Nice! Thanks! basedmypy being a nice alternative to the “full featured” pylance should be compelling for a lot of non-vscode users :)

**Comment by KotlinIsland** [comment]
> Nice! Thanks! basedmypy being a nice alternative to the “full featured” pylance should be compelling for a lot of non-vscode users :)

Hopefully, basedpyright will be compelling to all vscode users as well, as it's aiming to fix a lot of existing issues.
