### ISSUE TITLE
basedpyright.analysis.typeCheckingMode appears to still default to "all" in v1.19.0

### ISSUE THREAD

**Issue by heygarrett** [DetachHead/basedpyright#785]
If I run `basedpyright` from the command line it correctly reports missing types as warnings. But inside Neovim I'm seeing missing types reported as errors. This is without any changes to the configuration beyond what's provided by [nvim-lspconfig](https://github.com/neovim/nvim-lspconfig/blob/master/lua/lspconfig/configs/basedpyright.lua#L52):

```lua
basedpyright = {
  analysis = {
    autoSearchPaths = true,
    diagnosticMode = "openFilesOnly",
    useLibraryCodeForTypes = true
  }
}
```

If I explicitly configure it to use "recommended" the missing types are correctly reported as warnings:

```lua
lspconfig["basedpyright"].setup({
	settings = {
		basedpyright = {
			analysis = { typeCheckingMode = "recommended" },
		},
	},
})
```

Neovim version:

```
❯ nvim -v
NVIM v0.10.2
Build type: Release
LuaJIT 2.1.1727870382
Run "nvim -V1 -v" for more info
```

basedpyright version:

```
❯ basedpyright --version
basedpyright 1.19.0
based on pyright 1.1.385
```

Python version:

```
❯ python3 --version
Python 3.13.0
```

**Comment by DetachHead** [comment]
is it the same if you run `basedpyright` in the command line?

**Comment by heygarrett** [comment]
No, it correctly reports missing types as warnings when running `basedpyright` on the command line.

**Comment by DetachHead** [comment]
sorry i somehow missed your very first sentence where you said that already lol

it could be [a similar situation to the sublime text plugin](https://github.com/sublimelsp/LSP-basedpyright/issues/44) where they define their own copy of the default settings, in which case you may need to raise an issue there to get them to update it.

**Comment by heygarrett** [comment]
As far as I can tell the only default settings are provided by nvim-lspconfig:

```
basedpyright = {
  analysis = {
    autoSearchPaths = true,
    diagnosticMode = "openFilesOnly",
    useLibraryCodeForTypes = true
  }
}
```

But I'll try starting the LSP server manually to see if I can reproduce it without setting anything.

**Comment by heygarrett** [comment]
I can confirm that starting the language server myself, without using the config provided by nvim-lspconfig, does reproduce the issue:

```lua
local group = vim.api.nvim_create_augroup("basedpyright", { clear = true })
vim.api.nvim_create_autocmd("FileType", {
	group = group,
	pattern = "python",
	callback = function()
		vim.lsp.start({
			name = "basedpyright",
			cmd = { "basedpyright-langserver", "--stdio" },
			single_file_support = true,
		})
	end,
})
```

**Comment by heygarrett** [comment]
Sorry to stump you. 😅 I'll try to put together a minimal repro as soon as I'm able.

**Comment by heygarrett** [comment]
Actually, the snippet I used to start the language server myself serves as a minimal repro:

```lua
-- repro.lua

local group = vim.api.nvim_create_augroup("basedpyright", { clear = true })
vim.api.nvim_create_autocmd("FileType", {
	group = group,
	pattern = "python",
	callback = function()
		vim.lsp.start({
			name = "basedpyright",
			cmd = { "basedpyright-langserver", "--stdio" },
			single_file_support = true,
		})
	end,
})
```

```python
# test.py

def testing(param):
	print(param)
```

Steps to reproduce:

0. Have basedpyright in your PATH
1. `nvim -u repro.lua test.py`
2. See errors for missing type annotations

**Comment by DetachHead** [comment]
oh i see whats going on now. it was still defaulting to `"all"` in the language server config but only if there's no `tool.basedpyright` section in `pyproject.toml`
