### ISSUE TITLE
Inlay hints, function return types : short flicker when adding whitespace around function colon

### ISSUE THREAD

**Issue by Altonss** [DetachHead/basedpyright#794]
When switching from

```
def foo(a):
    return a
```
to (added whitespace after or before the `:`):
```
def foo(a): 
    return a
```

The function return types inlay hints shortly switches from ` -> Any` to ` -> An...` before going back to normal state. This flickering isn't very elegant :)

System info:
Vscodium 1.94.2 (flatpak, linux)
BasedPyright v1.19.0 (from https://open-vsx.org/extension/detachhead/basedpyright)

**Comment by DetachHead** [comment]
thanks. closing in favor of that issue
