### ISSUE TITLE
Setting `python.pythonPath` doesn't seem to help resolve imports when not in a virtual environment shell

### ISSUE THREAD

**Issue by tristan957** [DetachHead/basedpyright#807]
First of all, thanks so much for your awesome work on this!

When I enter my `poetry shell`, and then launch neovim, everything works swimmingly: imports resolve, diagnostics work, etc. I'd like to remove the `poetry shell` step from my workflow, if possible. Based upon my reading of `python.pythonPath`, I thought all I would need to do is set that language server setting to the output `poetry env info --executable`, but that doesn't seem to work, meaning imports don't resolve. I've confirmed `basedpyright` has the correct setting for `python.pythonPath`.

I'm sure this is a config issue on my side or a misunderstanding of the documentation.

**Comment by tristan957** [comment]
This seems like a language server lifetime issue, and I can't figure it out. For some reason if I send the request (workspace/didChangeConfiguration) after the [initialize](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#initialize) step it doesn't work. However, if I delay it, it works.

```
      • {on_init}?            (`elem_or_list<fun(client: vim.lsp.Client, initialize_result: lsp.InitializeResult)>`)
                              Callback invoked after LSP "initialize", where
                              `result` is a table of `capabilities` and
                              anything else the server may send. For example,
                              clangd sends `initialize_result.offsetEncoding`
                              if `capabilities.offsetEncoding` was sent to it.
                              You can only modify the `client.offset_encoding`
                              here before any notifications are sent.
```

Gonna close this issue. I guess `on_init` is not the solution to this problem.

**Comment by tristan957** [comment]
Sorry for wasting your time.

**Comment by tristan957** [comment]
Anyway, here is how I solved the problem for anyone else using Neovim and lspconfig:

```
local capabilities = require("tristan957.lsp").capabilities

return {
  capabilities = capabilities,
  settings = {
    basedpyright = {
      analysis = {
        autoImportCompletions = true,
        autoSearchPaths = true,
        diagnosticMode = "openFilesOnly",
        diagnosticSeverityOverrides = {
          reportUnusedCallResult = false,
        },
        useLibraryCodeForTypes = true,
      },
    },
  },
  ---@param new_config vim.lsp.ClientConfig
  ---@param new_root_dir string
  on_new_config = function(new_config, new_root_dir)
    local default_config = require("lspconfig.configs.basedpyright").default_config

    -- We are already in the virual environment, so skip the setup.
    if vim.env.VIRTUAL_ENV ~= nil then
      return
    end

    if
      vim.fn.filereadable(vim.fs.joinpath(new_root_dir, "poetry.lock")) == 1
      and vim.fn.executable("poetry") == 1
    then
      new_config.cmd = { "poetry", "run", "--", table.unpack(default_config.cmd) }
    end
  end,
}
```

**Comment by DetachHead** [comment]
no worries, if you manage to narrow it down to something specific that (based)pyright language server is doing wrong, let me know and we can re-open this issue if needed

**Comment by tristan957** [comment]
It's probably some race condition either in basedpyright or neovim. Don't know enough about either to say for sure what is going on.
