### ISSUE TITLE
no error when subtyping attribute with incompatible type

### ISSUE THREAD

**Issue by DetachHead** [DetachHead/basedpyright#808]
Code sample in [basedpyright playground](https://basedpyright.com/?typeCheckingMode=all&reportImplicitStringConcatenation=false&reportUnusedExpression=false&code=MYGwhgzhAECCBcBYAUNN0BuYQFcCm0AvNAIwrnKiQwBCAFLAJRKrpa4HEByA9gHZ4gA)

```python
class A:
    value = 1


class B(A):
    value = None
```

**Comment by karolyi** [comment]
Coming from the django angle, this seems to be a huge undertaking if we (djangoers) truly want to have basedpyright to check out without warnings/errors.

If you know django models, you know that their attirbutes (the DB fields, practically) are defined on the classes, which are converted into actual actionable fields on the metaclass call. [Here's a django model](https://docs.djangoproject.com/en/4.2/topics/db/models/#quick-example), for example.

As you can see, upgrading projects to fit this rule isn't really worth it. Luckily we can just use `--writebaseline` on the file to make the warnings go away.

Nonetheless, I figured I'd add this tidbit of information. I know that the way django does its things is not always commendable, but for historical reasons, it is what it is.

**Comment by DetachHead** [comment]
thanks for the info. ideally this new rule wouldn't exist and we would instead just check that the attribute type is correct even if it doesn't have a type annotation, but i figured this was the best compromise since i don't want to risk impacting performance by changing code i barely understand. in this case i saw a comment that specifically said this decision was made for performance reasons so i figured it would be a bad idea to ignore that.

if you don't need subclasses you can work around it by using the `@final` decorator which will suppress the warning:

```py
from django.db import models
from typing import final

@final
class Person(models.Model):
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
```

you can also just disable the rule entirely if you want:

```toml
[tool.basedpyright]
reportUnannotatedClassAttribute = false
```

but if you do want to add explicit type annotations on new code and just don't want to have to update hundreds of lines of existing code then yeah using the baseline file is probably the way to go
