### ISSUE TITLE
1.19.1 regression: Failed to parse pyproject.toml when it contains emoji

### ISSUE THREAD

**Issue by shoucandanghehe** [DetachHead/basedpyright#819]
![f5d7f3f941fbd17585308afd97086db0](https://github.com/user-attachments/assets/fd0dfee8-c7ca-4838-a24f-596a795f3837)
![b14b399385381c8b9e1249513cc42214](https://github.com/user-attachments/assets/c107642f-6720-4d60-867c-3ee85a96a45e)
It can be solved by using the GitHub Markdown style emoji like `:bookmark:`

**Comment by KotlinIsland** [comment]
the toml parser was changed in version [1.19.1](https://github.com/DetachHead/basedpyright/releases/tag/v1.19.1), was this working previously?

**Comment by shoucandanghehe** [comment]
> the toml parser was changed in version [1.19.1](https://github.com/DetachHead/basedpyright/releases/tag/v1.19.1), was this working previously?

yes, i tested 1.19.0 and it work fine

**Comment by DetachHead** [comment]
raised upstream at https://github.com/sunnyadn/js-toml/issues/2

in the mean time i'll see if i can find another toml parser. but there doesn't seem to be many options

**Comment by KotlinIsland** [comment]
https://jsr.io/@std/toml could we use this?
