### ISSUE TITLE
VSCode: Renaming (any) file in the filetree is very long 

### ISSUE THREAD

**Issue by FBorowiec** [DetachHead/basedpyright#826]
![Screenshot from 2024-10-29 12-10-14](https://github.com/user-attachments/assets/a574ec05-0234-42e7-a7ad-495a1e6d6991)
Hi! First of all, let me tell you what a great tool `basedpyright` is.
Unfortunately when using VSCode's extension: `detachhead.basedpyright` when I rename (any) file in VSCode's file tree it takes an incredibly long time.
Is there a setting to prevent the file watcher from looking for all the file types?
Thanks!

**Comment by DetachHead** [comment]
yeah it takes ages for me on a large codebase as well. the pylance one is pretty much instant. maybe #427 is relevant?

**Comment by FBorowiec** [comment]
probably, although the confusing part for me is why does that happen to any file (in my case cpp and starlark files) where no python file is even opened?

**Comment by FBorowiec** [comment]
just checked that `ms-pyright.pyright` doesn't present that issue
