### ISSUE TITLE
Throws error in monorepo that has a package.json at the toplevel

### ISSUE THREAD

**Issue by vikigenius** [DetachHead/basedpyright#861]
I have a monorepo that has both a pyproject.toml and a package.json at the toplevel

I install basedpyright in my virtual environment:

Using 

`uv add --dev basedpyright`

It seems like basedpyright is somehow using my package.json when it shouldn't

```
file:///home/void/Projects/Python/chatpyre/.venv/lib/python3.12/site-packages/basedpyright/index.js:6
global.__rootDirectory = __dirname + '/dist/';
                         ^

ReferenceError: __dirname is not defined in ES module scope
This file is being treated as an ES module because it has a '.js' file extension and '/home/void/Projects/Python/chatpyre/package.json' contains "type": "module". To treat it as a CommonJS script, rename it to use the '.cjs' file extension.
    at file:///home/void/Projects/Python/chatpyre/.venv/lib/python3.12/site-packages/basedpyright/index.js:6:26
    at ModuleJob.run (node:internal/modules/esm/module_job:268:25)
    at async onImport.tracePromise.__proto__ (node:internal/modules/esm/loader:543:26)
    at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:116:5)

Node.js v22.11.0
```

**Comment by DetachHead** [comment]
oh wow, i also have a project with both a top-level `pyproject.toml` and `package.json` but never ran into this issue because it doesn't use `"type": "module"`

**Comment by vikigenius** [comment]
Yep. I tried a bunch of things and don't know if there is a way to have something that works for both cjs and module.

There also doesn't seem to be a way to ignore the package.json

The easiest solution is probably to also bundle a minimal package.json alongside the index.js file to make sure it only uses that one.

**Comment by vikigenius** [comment]
Adding an empty package.json alongside `index.js` fixes this issue
