### ISSUE TITLE
`diagnosticSeverityOverrides` and `typeCheckingMode` LSP client settings ignored

### ISSUE THREAD

**Issue by betaprior** [DetachHead/basedpyright#867]
The following is being sent by my LSP client (emacs `lsp-pyright`):

```
[Trace - 03:26:48 AM] Sending response 'workspace/configuration - (1)'. Processing request took 0ms
Params: {
  "jsonrpc": "2.0",
  "id": 1,
  "result": [
    {
      "analysis": {
        "diagnosticSeverityOverrides": {
          "reportUnknownArgumentType": "none"
        },
        "typeCheckingMode": "off",
        "autoImportCompletions": true,
        "diagnosticMode": "openFilesOnly",
        "logLevel": "info",
        "autoSearchPaths": true,
        "extraPaths": []
      },
      "pythonPath": "/home/leo/opt/miniconda3/bin/python",
      "venvPath": ""
    }
  ]
}
```

Despite these settings, all type checking errors are coming through at a warning severity level. It is possible to force set `typeCheckingMode` via `pyrightconfig.json`, but the LSP client setting is ignored.

Both of these settings work as expected in vanilla pyright (for example, if I use `"typeCheckingMode": "strict"` all the type errors appear with a severity of 1, except for those listed in `diagnosticSeverityOverrides`).

**Comment by DetachHead** [comment]
do you have a `pyproject.toml` file with a `[tool.basedpyright]` or `[tool.pyright]` section in your project? if so, it overrides the lsp config. [see here for mroe info](https://docs.basedpyright.com/latest/configuration/config-files/#overriding-language-server-settings)

i want to add a warning to the user when this occurs, see https://github.com/DetachHead/basedpyright/issues/513#issuecomment-2364928299

**Comment by betaprior** [comment]
> do you have a `pyproject.toml` file with a `[tool.basedpyright]` or `[tool.pyright]` section in your project? if so, it overrides the lsp config. [see here for more info](https://docs.basedpyright.com/latest/configuration/config-files/#overriding-language-server-settings)

No, this was with a blank test project with a single python file, in an empty git repo.

**Comment by DetachHead** [comment]
im not familiar with emacs, what does your config file look like?

**Comment by betaprior** [comment]
> im not familiar with emacs, what does your config file look like?

I found the bug in the LSP config that shipped with doom emacs distro. Unfortunate that the logs looked fine so I had to source-dive. Thanks for rubber-ducking this!
