### ISSUE TITLE
Insert inline gray type annotation into source code

### ISSUE THREAD

**Issue by DeeliN221** [DetachHead/basedpyright#896]
![image](https://github.com/user-attachments/assets/3dc68bf0-10dc-4b77-b456-f857f3b8f570)

```lua
  spec = {
    { "LazyVim/LazyVim", import = "lazyvim.plugins" },
    { import = "lazyvim.plugins.extras.lang.python" },
    { import = "lazyvim.plugins.extras.vscode" },
    { import = "plugins" },
  },
```
Enabling Lazyvim python language extensions, basedpyright by default shows inline type annotation and hints in gray font, `: str` and `path=` in the example, I wonder how to insert these into python source code?

**Comment by DetachHead** [comment]
i want to add a double click action to do this - see #198 

im not sure if this functionality is possible in the language server or if it's vscode specific

**Comment by DetachHead** [comment]
looks like this is indeed possible in the language server ([see the `textEdits` arrray](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#inlayHint)), so closing this in favor of #198
