### ISSUE TITLE
Suggestions for reportExplicitAny?

### ISSUE THREAD

**Issue by oguzhanmeteozturk** [DetachHead/basedpyright#910]
Any suggestions for these cases?

```python
_T_contra = TypeVar("_T_contra", contravariant=True)

class Comparable(Protocol[_T_contra]):
    """A type that supports comparison operations."""

    __slots__: tuple[str, ...] = ()

    def __lt__(self, value: _T_contra, /) -> bool: ...
    def __gt__(self, value: _T_contra, /) -> bool: ...
    def __ge__(self, value: _T_contra, /) -> bool: ...
    @override
    def __eq__(self, value: object, /) -> bool: ...
    @override
    def __hash__(self) -> int: ...


_K = TypeVar("_K", bound="Comparable[Any]") # Type Any is not allowed
```

[Playground](http://basedpyright.com/?pyrightVersion=1.22.0&typeCheckingMode=all&code=GYJw9gtgBALgngBwJYDsDmUkQWEMoAqiApgGoCGIANFAArgxgDGYANjWAG7EghIAmxGgEEUcAFCSA%2BgSksUMEOSgBeQiQogAFACIZcsAqU6a8xeU6Uk5BSoIgArsQCUkpq3IBnT1ADCkBEpyACNWYi16MEYWVgBtfTMlAF1nAC5xKEyoHRzhWBJYAAtyfE8HBBw8HxZsK09DKDAEHhKkQ08AOhydSSyoKSlPVijPAdTYcrDYz0UaDvmk1SgtVwyswWB%2BqVYYAa1PYlZgGktWJ3GEw3MaAHpnKABaAD4oYLA2cfmOtcyNrbRdlJ9odjlBTud%2BrJEuRbvdnq93qxPvMflA-gM0MQ9gcjidyGdiBcoVclLDHi83h8oF9UQABLg8PiCVHoqTEACO2JBeIJ4zAwQAVsQmDAyfDKUjqSi%2BvTuLwBMQWcRNgNip5ClyjnCXqgYMjvtIANJLIjNTS6KSGkwIhwofgqHT%2BWpKULEWKiOBJHT3ADE6maUA9mB8KCiUHxwwA7sR%2BEA)

_K = TypeVar("_K", bound="Comparable[object]") Maybe? Doesn't seem like a improvement really

**Comment by oguzhanmeteozturk** [comment]
Sorry my bad object doesn't work at all:
[Playground](http://basedpyright.com/?typeCheckingMode=all&code=GYJw9gtgBALgngBwJYDsDmUkQWEMoAqiApgGoCGIANFAArgxgDGYANjWAG7EghIAmxGgHFiKHkiY0AgijgAoRQH0CSlihghyUALyESFEAAoARCrVgNWkzXWbynSknIadBEAFdiASkVNW5ADOgVAAwpAIlOQARqzERvRgjCysANrmdloAut4AXPJQhVAmJdKwJLAAFuT4gR4IOHghLNhOgZZQYAg8NUiWgQB0JSaKRVBKSoGsSYETubD1camBmjQD61m6UEa%2BBUWCwONKrDATRoHErMA0jqxe8xmW9jQA9N5QALQAfFDRYGzzdYDPaFA5HNCnJTnS7XKC3e7jVSZcivd7fX7-ViA9YgqBgiZoYhnC5XG7kO7EB5Ip5aVGfH5-AFQIG4gACXB4fEEuPxSmIAEdiTCyRT5mBogArYhMGB09GMrHMnFjdncXgCYg84iHCbVQKVIVXNE-VAwbHA5QAaS2RG6hlMSktNgxHhQ-B0JnCrS0sWIqVkcCyJneAGJ9N0oAHMCEUEkoOTpgB3Yj8eRKUg2gyUB2kYN%2BALBKAAZUg8VE4j4THSlpo6Zy%2BTGkWCinaEGIOhLbeWqygKxAWR2ijTloATJm7dmzKPnX9Xe7PREor7UuKpTKg%2B806Qx3pbWRJ%2BmR3n5P4giFO8QR0ZyxIq46R7Xt-XcU3Ai3Sx3SyPu9Re5oB6G4bEMUfYmFATAuLG%2BDRMBZ5IGg4j8LAYDlBGjh8DEcTFPerIXkeuJjIRRFjGGe4gZoYFIDGcZwQhmHAYwUD1N0IAum6xRepEPpLKu0owEGUDALgqHAehzi%2Btho64V%2BIzyGGADqlRIFh8ARn2UB6lUwEgAKHhIDpSFtjAlRgPwIQHKgKbyEAA)

**Comment by DetachHead** [comment]
since that generic is contravariant, the widest possible  type to use there is `Comparable[Never]` instead of `Comparable[object]`

**Comment by oguzhanmeteozturk** [comment]
Thank you!
