### ISSUE TITLE
refactor helper renaming a file that shadows basedpyright modifies the extension itself

### ISSUE THREAD

**Issue by NSQY** [DetachHead/basedpyright#927]
v1.22.1
Windows 11
vscode 1.95.3

1. create main.py
2. create enum.py
3. rename enum.py to foo.py

![image](https://github.com/user-attachments/assets/08d51cfb-9920-42e9-ac14-19658eede19d)

**Comment by DetachHead** [comment]
this is odd, i was able to reproduce this issue once but not a second time. it should only be checking source files and filtering out typeshed files, but it seems to sometimes not do that for some reason. need to investigate further
