### ISSUE TITLE
feature: go to implementation / list implementations

### ISSUE THREAD

**Issue by disrupted** [DetachHead/basedpyright#958]
the Pylance team rolled out preliminary support for go to implementation in the latest pre-release. https://github.com/microsoft/pylance-release/releases/tag/2024.12.100 and more specifically https://github.com/microsoft/pylance-release/issues/4329

They are also further discussing the subject in https://github.com/microsoft/pylance-release/issues/6775. Afaict this feature won't be available in Pyright.

Are there any plans to support this feature in BasedPyright?

**Comment by DetachHead** [comment]
i've looked into this before and from what i remember there doesn't seem to be a language server feature for this, so it would need to be implemented in the vscode extension.

@KotlinIsland we already have an issue for this right? i can't find it

**Comment by disrupted** [comment]
Could you elaborate what you mean by that? Afaict `textDocument/implementation` is part of the official LSP spec. https://microsoft.github.io/language-server-protocol/specifications/specification-3-14/#textDocument_implementation

**Comment by DetachHead** [comment]
im probably misremembering then, i remember commenting about the situation on the existing issue but i cant find it lol

**Comment by KotlinIsland** [comment]
- are you thinking of #355?

**Comment by DetachHead** [comment]
thanks, closing in favor of that issue
